// GENERATED by tools/pack_function.py from index.html — do not edit here (decision 95).
// The page's own maths and names for the scudi-notify function: the Scudi engine block, the team-name aliases,
// the competitions' ESPN slugs. Rebuilt whenever index.html changes; the tests check it is in step.
/* eslint-disable */
/* ===== Scudi slip maths (shared by the page and the tests) ===== */
var Scudi = (function () {
  var N = 10, FACT = [1], i0;
  for (i0 = 1; i0 < N; i0++) FACT[i0] = FACT[i0 - 1] * i0;
  /* first half: 0.434 of each side's expected goals, low-score correction -0.040 (fitted on 71,589 half-time scores,
     2005-06 to 2016-17; mirrors scudi_slips/matrix.py) */
  var HALF_SHARE = 0.434, HALF_RHO = -0.040, BTTS_SHIFT = 0.015;
  function safeRho(lh, la, rho) { var hi = Math.min(1 / (lh * la), 1) * 0.999, lo = -Math.min(1 / lh, 1 / la) * 0.999; return Math.max(lo, Math.min(hi, rho)); }
  /* Dixon–Coles score matrix from two expected-goals numbers and the low-score correction the price job fitted */
  function matrix(lh, la, rho) {
    rho = safeRho(lh, la, rho == null ? -0.06 : rho);
    var m = new Float64Array(N * N), tot = 0, h, a, i;
    for (h = 0; h < N; h++) for (a = 0; a < N; a++) {
      var t = 1;
      if (h === 0 && a === 0) t = 1 - lh * la * rho; else if (h === 0 && a === 1) t = 1 + lh * rho;
      else if (h === 1 && a === 0) t = 1 + la * rho; else if (h === 1 && a === 1) t = 1 - rho;
      m[h * N + a] = Math.exp(-lh) * Math.pow(lh, h) / FACT[h] * Math.exp(-la) * Math.pow(la, a) / FACT[a] * t;
      tot += m[h * N + a];
    }
    for (i = 0; i < N * N; i++) m[i] /= tot;
    var o = { home: 0, draw: 0, away: 0, o15: 0, o25: 0, u35: 0, btts: 0, grid: [], scores: [], m: m };
    for (i = 0; i < 5; i++) o.grid[i] = [0, 0, 0, 0, 0];
    for (h = 0; h < N; h++) for (a = 0; a < N; a++) {
      var p = m[h * N + a];
      if (h > a) o.home += p; else if (h === a) o.draw += p; else o.away += p;
      if (h + a >= 2) o.o15 += p;
      if (h + a >= 3) o.o25 += p;
      if (h + a <= 3) o.u35 += p;
      if (h >= 1 && a >= 1) o.btts += p;
      o.grid[Math.min(h, 4)][Math.min(a, 4)] += p;
      if (h < 5 && a < 5) o.scores.push({ h: h, a: a, p: p });
    }
    o.scores.sort(function (x, y) { return y.p - x.p; });
    return o;
  }
  function half(lh, la) { return matrix(lh * HALF_SHARE, la * HALF_SHARE, HALF_RHO); }
  function logit(p) { p = Math.min(Math.max(p, 1e-6), 1 - 1e-6); return Math.log(p / (1 - p)); }
  function sigmoid(x) { return 1 / (1 + Math.exp(-x)); }

  /* ---------- every pick type (mirrors scudi_slips/picks.py) ----------
     Classic picks (result, double chance, goals, both score) as before. New ones (decision 78): multigol, team goals,
     combos, 1X2 handicap, first half; each from the same score matrix, then the calibration correction fitted on
     2005-06 to 2016-17 and checked on 2017-18 to 2025-26. Types that failed the check are known (so a pasted SNAI
     price or an old slip still reads) but never offered. */
  var MARKETS = [], BY_ID = {};
  function add(mk) { MARKETS.push(mk); BY_ID[mk.id] = mk; mk.mask = []; for (var h = 0; h < N; h++) for (var a = 0; a < N; a++) if (mk.wins(h, a)) mk.mask.push(h * N + a); return mk; }
  var H = function (m) { return m.home; }, A = function (m) { return m.away; };
  add({ id: '1', group: 'Result', classic: true, base: 0.050, wins: function (h, a) { return h > a; }, p: function (c) { return c.home; }, label: function (m) { return m.home + ' win'; } });
  add({ id: 'X', group: 'Result', classic: true, base: 0.050, wins: function (h, a) { return h === a; }, p: function (c) { return c.draw; }, label: function () { return 'Draw'; } });
  add({ id: '2', group: 'Result', classic: true, base: 0.050, wins: function (h, a) { return h < a; }, p: function (c) { return c.away; }, label: function (m) { return m.away + ' win'; } });
  add({ id: '1X', group: 'Double chance', classic: true, base: 0.062, wins: function (h, a) { return h >= a; }, p: function (c) { return c.home + c.draw; }, label: function (m) { return m.home + ' or draw'; } });
  add({ id: 'X2', group: 'Double chance', classic: true, base: 0.062, wins: function (h, a) { return h <= a; }, p: function (c) { return c.away + c.draw; }, label: function (m) { return m.away + ' or draw'; } });
  add({ id: '12', group: 'Double chance', classic: true, base: 0.062, wins: function (h, a) { return h !== a; }, p: function (c) { return c.home + c.away; }, label: function () { return 'No draw'; } });
  add({ id: 'O15', group: 'Goals', classic: true, base: 0.058, wins: function (h, a) { return h + a >= 2; }, p: function (c) { return c.o15; }, label: function () { return 'Over 1.5 goals'; } });
  add({ id: 'O25', group: 'Goals', classic: true, base: 0.058, wins: function (h, a) { return h + a >= 3; }, p: function (c) { return c.o25; }, label: function () { return 'Over 2.5 goals'; } });
  add({ id: 'U25', group: 'Goals', classic: true, base: 0.058, wins: function (h, a) { return h + a <= 2; }, p: function (c) { return 1 - c.o25; }, label: function () { return 'Under 2.5 goals'; } });
  add({ id: 'U35', group: 'Goals', classic: true, base: 0.058, wins: function (h, a) { return h + a <= 3; }, p: function (c) { return c.u35; }, label: function () { return 'Under 3.5 goals'; } });
  add({ id: 'GG', group: 'Both score', classic: true, base: 0.066, wins: function (h, a) { return h >= 1 && a >= 1; }, p: function (c) { return Math.min(0.99, c.btts + BTTS_SHIFT); }, label: function () { return 'Both teams score'; } });
  add({ id: 'NG', group: 'Both score', classic: true, base: 0.066, wins: function (h, a) { return h === 0 || a === 0; }, p: function (c) { return Math.max(0.01, 1 - c.btts - BTTS_SHIFT); }, label: function () { return 'Not both score'; } });
  var CORR = { 'MG1-2': [-0.0016, 0.927], 'MG1-3': [0.0574, 0.9312], 'MG1-4': [0.1366, 0.9237], 'MG1-5': [0.3954, 0.8042], 'MG1-6': [-0.2255, 1.1318], 'MG2-3': [-0.0563, 0.7654],
    'MG2-4': [0.0882, 0.7599], 'MG2-5': [0.0334, 0.9193], 'MG2-6': [0.0003, 0.9667], 'MG3-4': [0.0355, 1.0445], 'MG3-5': [0.0106, 1.0285], 'MG3-6': [0.0064, 1.0235], 'MG4-6': [0.0142, 1.0065],
    'HO05': [0.0272, 1.0164], 'HO15': [-0.0013, 1.0086], 'HU15': [0.0013, 1.0086], 'HU25': [0.0865, 0.9925], 'AO05': [0.0921, 0.9062], 'AO15': [-0.0629, 0.9037], 'AU15': [0.0629, 0.9037],
    'AU25': [0.2172, 0.8972], 'HMG1-2': [0.0929, 0.9386], 'HMG1-3': [0.0681, 1.0142], 'AMG1-2': [0.0751, 0.7843], 'AMG1-3': [0.0946, 0.8879],
    '1+O15': [-0.0374, 1.0084], '1+O25': [-0.03, 1.0014], '1+U35': [0.0453, 1.0086], '1+GG': [0.0859, 1.0347], 'X+U25': [0.247, 1.2071], 'X+U35': [0.247, 1.2071], 'X+GG': [0.0307, 0.9841],
    '2+O15': [-0.0748, 0.9796], '2+O25': [-0.0857, 0.964], '2+U35': [0.0297, 1.0463], '2+GG': [-0.0008, 1.0043], '1X+O15': [-0.0013, 0.988], '1X+O25': [0.0038, 0.9882], '1X+U25': [0.0377, 1.0616],
    '1X+U35': [0.0157, 1.0431], '1X+GG': [0.0152, 0.9157], 'X2+O15': [-0.0226, 0.9418], 'X2+O25': [-0.0772, 0.915], 'X2+U25': [0.0442, 1.1034], 'X2+U35': [-0.0114, 1.0726], 'X2+GG': [-0.0041, 0.9512],
    '12+O15': [-0.0859, 1.0816], '12+O25': [-0.0334, 1.0214], '12+U35': [0.0331, 0.7947], '12+GG': [-0.0763, 0.8693], 'GG+O25': [-0.0345, 0.8266], 'GG+U35': [-0.0783, 0.8894],
    '1X+MG1-3': [0.0421, 1.0379], '1X+MG1-4': [0.0406, 1.0214], 'X2+MG1-3': [0.0124, 1.0513], 'X2+MG1-4': [0.017, 1.018], '12+MG2-4': [-0.0003, 1.2047], '12+MG2-5': [-0.0625, 1.1527],
    '1H-1': [-0.1233, 0.9856], 'XH-1': [0.2007, 1.0697], '2H-1': [-0.0034, 1.0042], '1H+1': [0.0229, 1.0095], 'XH+1': [0.1593, 1.0928], '2H+1': [-0.1434, 0.9572], '1H-2': [-0.1785, 0.9956],
    'XH-2': [0.0355, 1.0378], '2H-2': [0.1233, 0.9856], '1H+2': [0.1434, 0.9572], 'XH+2': [0.0424, 1.0387], '2H+2': [-0.3601, 0.8997],
    '1T1': [0.0098, 0.9937], '1TX': [0.0127, 1.0637], '1T2': [-0.0398, 0.9758], '1T1X': [0.0398, 0.9758], '1TX2': [-0.0098, 0.9937], '1T12': [-0.0127, 1.0637], '1TO05': [-0.017, 1.0816],
    '1TO15': [0.0186, 1.0283], '1TU15': [-0.0186, 1.0283], '1TU25': [0.0997, 0.9683], '1TU05': [0.017, 1.0816], '1TGG': [-0.3131, 0.7583], '1TNG': [0.3131, 0.7583] };
  [[1, 2], [1, 3], [1, 4], [1, 5], [1, 6], [2, 3], [2, 4], [2, 5], [2, 6], [3, 4], [3, 5], [3, 6], [4, 6]].forEach(function (r) {
    add({ id: 'MG' + r[0] + '-' + r[1], group: 'Multigol', wins: function (h, a) { return h + a >= r[0] && h + a <= r[1]; }, label: function () { return 'Multigol ' + r[0] + '–' + r[1]; } });
  });
  var TEAM = [['HO05', function (h) { return h >= 1; }, H, ' to score'], ['HO15', function (h) { return h >= 2; }, H, ' over 1.5 goals'], ['HU15', function (h) { return h <= 1; }, H, ' under 1.5 goals'],
    ['HU25', function (h) { return h <= 2; }, H, ' under 2.5 goals'], ['AO05', function (h, a) { return a >= 1; }, A, ' to score'], ['AO15', function (h, a) { return a >= 2; }, A, ' over 1.5 goals'],
    ['AU15', function (h, a) { return a <= 1; }, A, ' under 1.5 goals'], ['AU25', function (h, a) { return a <= 2; }, A, ' under 2.5 goals'], ['HU05', function (h) { return h === 0; }, H, ' not to score'],
    ['AU05', function (h, a) { return a === 0; }, A, ' not to score'], ['HMG1-2', function (h) { return h >= 1 && h <= 2; }, H, ' multigol 1–2'], ['HMG1-3', function (h) { return h >= 1 && h <= 3; }, H, ' multigol 1–3'],
    ['AMG1-2', function (h, a) { return a >= 1 && a <= 2; }, A, ' multigol 1–2'], ['AMG1-3', function (h, a) { return a >= 1 && a <= 3; }, A, ' multigol 1–3']];
  TEAM.forEach(function (t) { add({ id: t[0], group: 'Team goals', wins: t[1], label: function (m) { return t[2](m) + t[3]; } }); });
  var SHORT = { '1': function (m) { return m.home + ' win'; }, 'X': function () { return 'Draw'; }, '2': function (m) { return m.away + ' win'; }, '1X': function (m) { return m.home + ' or draw'; },
    'X2': function (m) { return m.away + ' or draw'; }, '12': function () { return 'No draw'; }, 'O15': function () { return 'over 1.5'; }, 'O25': function () { return 'over 2.5'; }, 'U25': function () { return 'under 2.5'; },
    'U35': function () { return 'under 3.5'; }, 'GG': function (m, first) { return first ? 'Both score' : 'both score'; }, 'NG': function (m, first) { return first ? 'Not both score' : 'not both score'; },
    'MG1-3': function () { return 'multigol 1–3'; }, 'MG1-4': function () { return 'multigol 1–4'; }, 'MG2-4': function () { return 'multigol 2–4'; }, 'MG2-5': function () { return 'multigol 2–5'; } };
  [['1', 'O15'], ['1', 'O25'], ['1', 'U35'], ['1', 'GG'], ['1', 'NG'], ['X', 'U25'], ['X', 'U35'], ['X', 'GG'], ['2', 'O15'], ['2', 'O25'], ['2', 'U35'], ['2', 'GG'], ['2', 'NG'],
    ['1X', 'O15'], ['1X', 'O25'], ['1X', 'U25'], ['1X', 'U35'], ['1X', 'GG'], ['X2', 'O15'], ['X2', 'O25'], ['X2', 'U25'], ['X2', 'U35'], ['X2', 'GG'], ['12', 'O15'], ['12', 'O25'], ['12', 'U35'], ['12', 'GG'],
    ['GG', 'O25'], ['GG', 'U35'], ['NG', 'U25'], ['NG', 'O15'], ['1X', 'MG1-3'], ['1X', 'MG1-4'], ['X2', 'MG1-3'], ['X2', 'MG1-4'], ['12', 'MG2-4'], ['12', 'MG2-5']].forEach(function (c) {
    var x = BY_ID[c[0]], y = BY_ID[c[1]];
    add({ id: c[0] + '+' + c[1], group: 'Combo', parts: c, wins: function (h, a) { return x.wins(h, a) && y.wins(h, a); }, label: function (m) { return SHORT[c[0]](m, true) + ' + ' + SHORT[c[1]](m, false); } });
  });
  [-1, 1, -2, 2].forEach(function (line) {
    ['1', 'X', '2'].forEach(function (side) {
      var id = side + 'H' + (line > 0 ? '+' : '-') + Math.abs(line);
      var lab = { '1H-1': function (m) { return m.home + ' win by 2+'; }, '2H-1': function (m) { return m.away + ' +1 (handicap)'; }, '1H+1': function (m) { return m.home + ' +1 (handicap)'; },
        '2H+1': function (m) { return m.away + ' win by 2+'; }, '1H-2': function (m) { return m.home + ' win by 3+'; }, '2H-2': function (m) { return m.away + ' +2 (handicap)'; },
        '1H+2': function (m) { return m.home + ' +2 (handicap)'; }, '2H+2': function (m) { return m.away + ' win by 3+'; },
        'XH-1': function (m) { return m.home + ' win by exactly 1'; }, 'XH+1': function (m) { return m.away + ' win by exactly 1'; },
        'XH-2': function (m) { return m.home + ' win by exactly 2'; }, 'XH+2': function (m) { return m.away + ' win by exactly 2'; } }[id];
      add({ id: id, group: 'Handicap', line: line, wins: function (h, a) { var d = h - a + line; return side === '1' ? d > 0 : side === 'X' ? d === 0 : d < 0; }, label: lab });
    });
  });
  [['1T1', function (h, a) { return h > a; }, function (m) { return '1st half: ' + m.home + ' win'; }], ['1TX', function (h, a) { return h === a; }, function () { return '1st half: draw'; }],
    ['1T2', function (h, a) { return h < a; }, function (m) { return '1st half: ' + m.away + ' win'; }], ['1T1X', function (h, a) { return h >= a; }, function (m) { return '1st half: ' + m.home + ' or draw'; }],
    ['1TX2', function (h, a) { return h <= a; }, function (m) { return '1st half: ' + m.away + ' or draw'; }], ['1T12', function (h, a) { return h !== a; }, function () { return '1st half: no draw'; }],
    ['1TO05', function (h, a) { return h + a >= 1; }, function () { return '1st half: over 0.5'; }], ['1TO15', function (h, a) { return h + a >= 2; }, function () { return '1st half: over 1.5'; }],
    ['1TU15', function (h, a) { return h + a <= 1; }, function () { return '1st half: under 1.5'; }], ['1TU25', function (h, a) { return h + a <= 2; }, function () { return '1st half: under 2.5'; }],
    ['1TU05', function (h, a) { return h + a === 0; }, function () { return '1st half: 0–0'; }], ['1TGG', function (h, a) { return h >= 1 && a >= 1; }, function () { return '1st half: both score'; }],
    ['1TNG', function (h, a) { return h === 0 || a === 0; }, function () { return '1st half: not both score'; }]].forEach(function (x) {
    add({ id: x[0], group: 'First half', half: true, wins: x[1], label: x[2] });
  });
  MARKETS.forEach(function (mk) { if (CORR[mk.id]) mk.corr = CORR[mk.id]; });
  /* never offered: NG and every pick that needs a team not to score (the matrix is too kind to them), the types that failed
     the check or confirm seasons, and those with no band to judge (all under 30%) */
  var NOT_OFFERED = {}; ['NG', '1+NG', '2+NG', 'NG+U25', 'NG+O15', 'HU05', 'AU05', 'AO05', 'AO15', 'X+GG', '2+U35', '1X+MG1-3', 'XH-1', 'XH+1', 'XH-2', 'XH+2', '1T1', '1TGG'].forEach(function (c) { NOT_OFFERED[c] = 1; });
  var GROUPS = ['Result', 'Double chance', 'Goals', 'Both score', 'Multigol', 'Team goals', 'Combo', 'Handicap', 'First half'];
  var OFFERED = MARKETS.filter(function (mk) { return !NOT_OFFERED[mk.id]; }).map(function (mk) { return mk.id; });
  var CLASSIC_IDS = MARKETS.filter(function (mk) { return mk.classic && !NOT_OFFERED[mk.id]; }).map(function (mk) { return mk.id; });

  /* every pick's fair chance for one match, computed once: from the price job's file where it carries the pick, otherwise
     from the match's score matrix. A live match whose file has no totals line gets no goals-based pick at all. */
  function chancesOf(match) {
    if (match._ch) return match._ch;
    var pre = match.pre && match.pre.chances || null, out = {}, ft = null, hf = null, noGoals = pre && pre.O25 === undefined;
    MARKETS.forEach(function (mk) {
      if (pre && pre[mk.id] !== undefined) { out[mk.id] = pre[mk.id]; return; }
      if (mk.classic) { if (!pre) out[mk.id] = mk.p(ft || (ft = match.calc || (match.calc = matrix(match.lh, match.la, match.rho)))); return; }
      if (noGoals || !(match.lh > 0 && match.la > 0)) return;
      var mm = mk.half ? (hf || (hf = match.calcH || (match.calcH = half(match.lh, match.la)))).m : (ft || (ft = match.calc || (match.calc = matrix(match.lh, match.la, match.rho)))).m, raw = 0;
      for (var i = 0; i < mk.mask.length; i++) raw += mm[mk.mask[i]];
      var p = mk.corr ? sigmoid(mk.corr[0] + mk.corr[1] * logit(raw)) : raw;
      if (mk.parts) p = Math.min(p, out[mk.parts[0]] == null ? 1 : out[mk.parts[0]], out[mk.parts[1]] == null ? 1 : out[mk.parts[1]]);
      out[mk.id] = Math.min(0.999, Math.max(0.001, p));
    });
    match._ch = out;
    return out;
  }
  /* example prices for the preview (the live file carries the price job's estimates) */
  function price(p, base, factor) {           /* margin grows a little on longer prices, as it does at real books */
    var m = (base + 0.02 * Math.max(0, Math.log(1 / p) - 0.3)) * (factor || 1);
    return Math.max(1.01, Math.round(100 / (p * (1 + m))) / 100);
  }
  /* markets no free feed prices: a typical SNAI-like margin, ASSUMED until pasted SNAI pages teach the real one
     (mirrors scudi_slips/feed.assumed_price) */
  var NEW_FLOOR = 0.30;
  var ASSUMED = { 'Multigol': 0.09, 'Team goals': 0.085, 'Combo': 0.11, 'Handicap': 0.085, 'First half': 0.085 };
  function assumedPrice(p, group) { var m = ASSUMED[group] + 0.02 * Math.max(0, Math.log(1 / p) - 0.3); return Math.max(1.01, Math.floor(100 / (p * (1 + m)) + 1e-9) / 100); }
  var SNAI_FLOOR = 1.25;
  /* the learned calibration (from the record, decision 78): a shift in log-odds per pick type and per competition */
  function learnedP(p, learned, id, lg) {
    if (!learned) return p;
    var d = (learned[id] || 0) + (learned['lg:' + lg] || 0);
    return d ? Math.min(0.995, Math.max(0.005, sigmoid(logit(p) + d))) : p;
  }
  /* haircut: once some real prices are typed in, every remaining estimate is scaled by how far SNAI sat from the
     estimates so far: per pick type (3+ prices), else per market group (3+), else the overall figure for the classic
     picks. The new markets' estimates already assume a SNAI-like margin, so they are not scaled by the overall figure. */
  function candidates(match, minLegOdds, actual, haircut, learned) {
    var ch = chancesOf(match), out = [], mine = Object.assign({}, match.snai || {}, (actual || {})[match.id] || {}), h = haircut || {}, est = match.pre && match.pre.estimate;
    MARKETS.forEach(function (mk) {
      if (NOT_OFFERED[mk.id]) return;
      var p0 = ch[mk.id]; if (p0 == null || !(p0 > 0 && p0 < 1)) return;
      if (!mk.classic && p0 < NEW_FLOOR) return;   /* the new markets were checked from 30% up: no longer shots */
      /* a match priced in the private store (decision 94) has no ordinary books' estimate: a SNAI-like margin until SNAI's own price is read */
      var base = est && est[mk.id] !== undefined ? est[mk.id] : mk.classic ? (match.pre && !match.priv ? null : price(p0, mk.base, 1)) : assumedPrice(p0, mk.group);
      if (base == null) return;
      var k = typeof h === 'number' ? h : (h[mk.id] || h['g:' + mk.group] || (mk.classic ? h.all : 0) || 1);
      var checked = mine[mk.id] !== undefined, o = checked ? mine[mk.id] : Math.max(1.01, Math.floor(base * k * 100 + 1e-9) / 100);
      var p = learnedP(p0, learned, mk.id, match.lg);
      if (o >= (checked ? SNAI_FLOOR : minLegOdds)) out.push({ id: mk.id, group: mk.group, label: mk.label(match), p: p, p0: p0, odds: o, cost: o * p - 1, checked: checked, half: !!mk.half });
    });
    return out;
  }
  /* how much the books disagreed on a pick (the price job's spread; derived picks borrow the nearest direct market) */
  var SIDE = { '1': '1', 'X': 'X', '2': '2', '1X': '1X', 'X2': 'X2', '12': '12', '1T1': '1', '1TX': 'X', '1T2': '2', '1T1X': '1X', '1TX2': 'X2', '1T12': '12' };
  function spreadOf(id, sp) {
    if (!sp) return null;
    var mk = BY_ID[id]; if (!mk) return null;
    if (mk.parts) { var a = spreadOf(mk.parts[0], sp), b = spreadOf(mk.parts[1], sp); return a == null || b == null ? (a == null ? b : a) : Math.sqrt(a * a + b * b); }
    if (SIDE[id] && sp[SIDE[id]] != null) return sp[SIDE[id]];
    if (mk.group === 'Handicap') return sp[id.charAt(0) === '1' ? '1' : '2'] != null ? sp[id.charAt(0) === '1' ? '1' : '2'] : null;
    return sp.O25 != null ? sp.O25 : null;
  }
  /* the picks a match may contribute under the user's rules; a locked pick overrides the rules. Each pick gets the weight
     the optimiser maximises (decision 78): its chance, lowered in prudent mode where the books disagree, nudged by the
     market's movement when signals are on, times its price to the power lambda (0 = highest chance, 1 = best return). */
  function menuFor(match, opts) {
    if ((opts.excluded || {})[match.id]) return [];
    var lock = (opts.locks || {})[match.id], list = candidates(match, opts.minLegOdds || SNAI_FLOOR, opts.actual, opts.haircut, opts.learned);
    if (lock) list = list.filter(function (c) { return c.id === lock; });
    else list = list.filter(function (c) {
      return (!opts.allowed || opts.allowed[c.id]) && (!opts.minChance || c.p >= opts.minChance) && (!opts.maxOdds || c.odds <= opts.maxOdds);
    });
    var lam = opts.lambda || 0;
    list.forEach(function (c) {
      var q = c.p;
      if (opts.prudent && match.spread) { var sd = spreadOf(c.id, match.spread); if (sd != null) { c.sd = sd; q = Math.max(0.005, q - opts.prudent * sd); } }
      if (opts.signals && match.sig && match.sig[c.id] != null) { c.drift = match.sig[c.id]; q *= Math.max(0.85, Math.min(1.15, Math.exp(1.5 * c.drift / c.p))); }
      c.w = q * (lam ? Math.pow(c.odds, lam) : 1);
    });
    if (opts.signals && !lock) list = list.filter(function (c) { return !(c.drift <= -0.03); });   /* the market has moved 3+ points against it */
    return list;
  }
  /* a pick another pick of the same match beats on both price and weight can never be in a best slip: dropping it
     changes no answer and makes the search much faster with 80+ pick types per match */
  function prune(list) {
    if (list.length < 2) return list;
    var s = list.slice().sort(function (a, b) { return b.odds - a.odds || b.w - a.w; }), out = [], best = -Infinity;
    s.forEach(function (c) { if (c.w > best * (1 + 1e-12)) { out.push(c); best = c.w; } });
    return out;
  }
  /* SNAI accumulator bonus: +3.5% compounded for every leg from the fifth, legs priced 1.25 or more, up to 30 legs */
  /* How far SNAI sits from the estimates, learned from every price typed in: one ratio per pick type once that
     type has 3 or more observations, then one per market group, otherwise the overall ratio. `memory` is earlier weeks' list. */
  function median(xs) { xs = xs.slice().sort(function (a, b) { return a - b; }); var n = xs.length; return n % 2 ? xs[(n - 1) / 2] : (xs[n / 2 - 1] + xs[n / 2]) / 2; }
  function ratiosFrom(matches, actual) {
    var out = [];
    matches.forEach(function (m) { var mine = (actual || {})[m.id]; if (!mine) return;
      var noHair = Object.assign({}, m, { snai: null });
      candidates(noHair, 1.01).forEach(function (c) { if (mine[c.id] !== undefined) out.push({ id: c.id, r: mine[c.id] / c.odds }); }); });
    return out;
  }
  function haircutFrom(matches, actual, memory) {
    var obs = (memory || []).concat(ratiosFrom(matches, actual)), by = {}, byG = {}, h = {};
    if (!obs.length) return { all: 1, n: 0 };
    obs.forEach(function (o) { (by[o.id] = by[o.id] || []).push(o.r); var g = BY_ID[o.id] && BY_ID[o.id].group; if (g) (byG[g] = byG[g] || []).push(o.r); });
    var clamp = function (x) { return Math.max(0.85, Math.min(1.05, x)); };
    var classic = obs.filter(function (o) { return BY_ID[o.id] && BY_ID[o.id].classic; });
    h.all = clamp(median((classic.length ? classic : obs).map(function (o) { return o.r; })));
    Object.keys(by).forEach(function (id) { if (by[id].length >= 3) h[id] = clamp(median(by[id])); });
    Object.keys(byG).forEach(function (g) { if (byG[g].length >= 3) h['g:' + g] = clamp(median(byG[g])); });
    h.n = obs.length;
    return h;
  }
  function snaiBonus(n) { return n >= 5 ? Math.pow(1.035, Math.min(n, 30) - 4) - 1 : 0; }

  /* ---------- the optimiser ----------
     One pick per used match, maximise the sum of log weights (with lambda 0 and no preferences: the chance that every leg
     wins) subject to combined odds >= target and to league rules ("at least 5 from Serie A", "at most 2 per league").
     The number of legs is either fixed (opts.legs) or free (opts.autoLegs: any number from 1 to opts.legs, the best one
     wins; with opts.rowTarget(k) the target can depend on the number of legs, e.g. when SNAI's bonus counts toward it).
     With lambda > 0 the bonus is part of the return, so each number of legs also gets lambda * log(1 + bonus).
     Dynamic programme on a grid of log-odds, two passes: rounded DOWN (a slip found always reaches the target),
     then rounded to NEAREST (kept only if its exact odds reach the target and it scores higher). */
  var NEG = -1e18;
  /* The cells of one row worth extending (decision 82): reachable, and not beaten by a cell further right (more odds) with
     at least the same score. Whatever follows a beaten cell does at least as well from the cell that beats it, so leaving
     beaten cells out changes no answer; it cuts the work several times over. Written into `out`, right to left. */
  function frontier(src, off, W, out) {
    var n = 0, best = NEG;
    for (var b = W - 1; b >= 0; b--) { var v = src[off + b]; if (v > best) { out[n++] = b; best = v; } }
    return n;
  }
  function stepsOf(list, B, D, nearest) {
    var ws = new Int32Array(list.length), lvs = new Float64Array(list.length);
    for (var j = 0; j < list.length; j++) { var st = Math.log(list[j].odds) / D; ws[j] = Math.min(B, nearest === 2 ? Math.ceil(st - 1e-9) : nearest ? Math.round(st) : Math.floor(st + 1e-9)); lvs[j] = Math.log(list[j].w || list[j].p); }
    return { ws: ws, lvs: lvs };
  }
  /* one match's picks added to every useful cell of `src`, written into `dst` (which already holds the "match not used"
     values, or nothing when the match must be used); ch/pv remember which pick and from which cell */
  function relax(src, dst, ch, pv, list, K, W, B, D, nearest, rowsReady, fr, sp) {
    sp = sp || stepsOf(list, B, D, nearest);
    var ws = sp.ws, lvs = sp.lvs, J = list.length, full = pv.length > K + 1;   /* full: a source cell for every cell (rules that bite) */
    for (var k = 0; k < K && k <= rowsReady; k++) {
      var off = k * W, to = (k + 1) * W, n = frontier(src, off, W, fr);
      for (var i = 0; i < n; i++) {
        var b = fr[i], v = src[off + b];
        for (var j = 0; j < J; j++) {
          var nb = b + ws[j]; if (nb > B) nb = B;
          var nv = v + lvs[j], at = to + nb;
          if (nv > dst[at]) { dst[at] = nv; ch[at] = j; if (full) pv[at] = b; else if (nb === B) pv[k + 1] = b; }
        }
      }
    }
  }
  function step(src, list, K, W, B, D, nearest, rowsReady, fr) {
    var best = new Float64Array((K + 1) * W).fill(NEG), ch = new Int8Array((K + 1) * W).fill(-1), pv = new Int32Array((K + 1) * W);
    relax(src, best, ch, pv, list, K, W, B, D, nearest, rowsReady, fr || new Int32Array(W));
    return { best: best, ch: ch, pv: pv };
  }
  function rowBonus(opts, k) { return opts.lambda ? opts.lambda * Math.log(1 + snaiBonus(k)) : 0; }
  function solveOnce(matches, menus, target, opts, nearest) {
    var K = opts.legs || matches.length, n = matches.length, D = opts.grid || 0.001, B = Math.ceil(Math.log(target) / D), W = B + 1, size = (K + 1) * W;
    var mustAll = !opts.autoLegs && K >= n, locks = opts.locks || {}, limits = opts.groupLimits || {}, order = [], seg = {}, i, j, k, b;
    matches.forEach(function (m, idx) { var g = m.lg; if (!seg[g]) { seg[g] = []; order.push(g); } seg[g].push(idx); });
    var cur = new Float64Array(size).fill(NEG), spare = new Float64Array(size), trail = [], done = 0, fr = new Int32Array(W); cur[0] = 0;
    for (var gi = 0; gi < order.length; gi++) {
      var g = order[gi], members = seg[g], lim = limits[g] || [0, opts.groupMax || null];
      var hi = Math.min(lim[1] == null ? K : lim[1], members.length, K), lo = Math.max(0, lim[0] || 0);
      if (lo > hi) return null;
      if (lo === 0 && hi >= Math.min(members.length, K)) {                 /* no rule bites */
        for (i = 0; i < members.length; i++) {
          var idx = members[i], forced = mustAll || !!locks[matches[idx].id], nxt = spare, chx = new Int8Array(size).fill(-1), pvx = new Int32Array(K + 1), sp = stepsOf(menus[idx], B, D, nearest);
          if (forced) nxt.fill(NEG); else nxt.set(cur);
          relax(cur, nxt, chx, pvx, menus[idx], K, W, B, D, nearest, done, fr, sp);
          trail.push({ kind: 0, idx: idx, ch: chx, pv: pvx, ws: sp.ws }); spare = cur; cur = nxt; done++;
        }
        continue;
      }
      var layers = [cur];                                                   /* a rule bites: layer j = legs this league has used */
      for (j = 1; j <= hi; j++) layers.push(new Float64Array(size).fill(NEG));
      for (i = 0; i < members.length; i++) {
        var id2 = members[i], f2 = mustAll || !!locks[matches[id2].id], steps = [], fresh = [f2 ? new Float64Array(size).fill(NEG) : layers[0]];
        var chs = new Int8Array((hi + 1) * size).fill(-1), pvs = new Int32Array((hi + 1) * size);
        for (j = 0; j < hi; j++) steps.push(step(layers[j], menus[id2], K, W, B, D, nearest, done, fr));
        for (j = 0; j < hi; j++) {
          var t = new Float64Array(size), o = (j + 1) * size;
          for (b = 0; b < size; b++) { var bs = f2 ? NEG : layers[j + 1][b]; if (steps[j].best[b] > bs) { t[b] = steps[j].best[b]; chs[o + b] = steps[j].ch[b]; pvs[o + b] = steps[j].pv[b]; } else t[b] = bs; }
          fresh.push(t);
        }
        layers = fresh; trail.push({ kind: 1, idx: id2, ch: chs, pv: pvs, size: size }); done++;
      }
      var merged = new Float64Array(size).fill(NEG), js = new Int8Array(size);
      for (j = lo; j <= hi; j++) for (b = 0; b < size; b++) if (layers[j][b] > merged[b]) { merged[b] = layers[j][b]; js[b] = j; }
      cur = merged; trail.push({ kind: 2, js: js });
    }
    var endK = K, endB = B;
    if (opts.autoLegs) {                                                  /* the best row (number of legs) that reaches its target */
      var bestV = NEG;
      for (var kk = 1; kk <= K; kk++) {
        var need = opts.rowTarget ? Math.min(B, Math.max(0, Math.ceil(Math.log(opts.rowTarget(kk)) / D))) : B, rb = rowBonus(opts, kk);
        for (var bb = need; bb <= B; bb++) { var v2 = cur[kk * W + bb]; if (v2 > NEG && v2 + rb > bestV) { bestV = v2 + rb; endK = kk; endB = bb; } }
      }
      if (bestV === NEG) return null;
    } else if (cur[K * W + B] === NEG) return null;
    var picks = []; k = endK; b = endB; j = 0;
    for (i = trail.length - 1; i >= 0; i--) {
      var t2 = trail[i], at = k * W + b, c;
      if (t2.kind === 2) j = t2.js[at];
      else if (t2.kind === 0) { c = t2.ch[at]; if (c >= 0) { picks.push({ match: matches[t2.idx], pick: menus[t2.idx][c] }); b = b === B ? t2.pv[k] : b - t2.ws[c]; k--; } }
      else { c = t2.ch[j * t2.size + at]; if (c >= 0) { picks.push({ match: matches[t2.idx], pick: menus[t2.idx][c] }); b = t2.pv[j * t2.size + at]; k--; j--; } }
    }
    return pack(picks, opts);
  }
  /* rules a finished slip must keep: locked picks in, league minimums and caps */
  function keepsRules(picks, opts) {
    var locks = opts.locks || {}, lim = opts.groupLimits || {}, by = {}, ids = {};
    picks.forEach(function (x) { by[x.match.lg] = (by[x.match.lg] || 0) + 1; ids[x.match.id] = x.pick.id; });
    if (Object.keys(locks).some(function (id) { return locks[id] && ids[id] !== locks[id]; })) return false;
    for (var g in by) { var L = lim[g] || [0, opts.groupMax || null]; if (L[1] != null && by[g] > L[1]) return false; }
    for (var g2 in lim) if ((by[g2] || 0) < (lim[g2][0] || 0)) return false;
    return true;
  }
  function pack(picks, opts) {
    var prob = 1, odds = 1, obj = 0;
    picks.forEach(function (x) { prob *= x.pick.p; odds *= x.pick.odds; obj += Math.log(x.pick.w || x.pick.p); });
    return { picks: picks, prob: prob, odds: odds, obj: obj + (opts && opts.autoLegs ? rowBonus(opts, picks.length) : 0) };
  }
  /* exact polish: one leg at a time, try every other pick of the same match and every pick of an unused match;
     keep a change when the slip still reaches its target, keeps the rules and scores higher. Repeats until nothing helps. */
  function polish(r, matches, menus, opts, need) {
    if (!r) return r;
    var improved = true, rounds = 0;
    while (improved && rounds++ < 20) {
      improved = false;
      for (var i = 0; i < r.picks.length && !improved; i++) {
        var used = {}; r.picks.forEach(function (x) { used[x.match.id] = 1; });
        for (var mi = 0; mi < matches.length && !improved; mi++) {
          var m = matches[mi]; if (m.id !== r.picks[i].match.id && used[m.id]) continue;
          for (var c = 0; c < menus[mi].length; c++) {
            if (menus[mi][c] === r.picks[i].pick) continue;
            var next = r.picks.slice(); next[i] = { match: m, pick: menus[mi][c] };
            var cand = pack(next, opts);
            if (cand.obj > r.obj + 1e-12 && cand.odds >= need(cand.picks.length) * (1 - 1e-12) && keepsRules(next, opts)) { r = cand; improved = true; break; }
          }
        }
      }
      if (!improved && opts.autoLegs) {                                    /* a leg fewer, if the rest still reaches */
        for (var d = 0; d < r.picks.length && !improved; d++) {
          var less = r.picks.slice(0, d).concat(r.picks.slice(d + 1));
          if (!less.length) continue;
          var cl = pack(less, opts);
          if (cl.obj > r.obj + 1e-12 && cl.odds >= need(less.length) * (1 - 1e-12) && keepsRules(less, opts)) { r = cl; improved = true; }
        }
      }
    }
    return r;
  }
  function solve(matches, target, opts) {
    opts = opts || {};
    var menus = matches.map(function (m) { return prune(menuFor(m, opts)); });
    var usable = menus.filter(function (l) { return l.length; }).length, legs = opts.legs || matches.length;
    if (opts.autoLegs) { legs = Math.min(legs, usable); if (legs < 1) return null; opts = Object.assign({}, opts, { legs: legs }); }
    else if (legs > usable || legs < 1) return null;
    var need = function (k) { return opts.autoLegs && opts.rowTarget ? opts.rowTarget(k) : target; };
    var reaches = function (r) { return r.odds >= need(r.picks.length) * (1 - 1e-12); };
    var better = function (a, b) { return a && reaches(a) && (!b || a.obj > b.obj) ? a : b; };
    var best = solveOnce(matches, menus, target, opts, false);
    if (opts.refine !== false) {
      best = better(solveOnce(matches, menus, target, opts, true), best);
      /* exactness: the pass that rounds every price UP can only overstate what is reachable, so its answer is an upper
         bound on the true best score. When that answer really reaches the target it IS the best slip; otherwise the grid
         is made finer (while it stays small) until the found slip is within 0.01% of the bound. */
      var o2 = opts, D = opts.grid || 0.001, picksN = menus.reduce(function (a, l) { return a + l.length; }, 0), tries = opts.exactTries == null ? 8 : opts.exactTries;
      for (var t = 0; t < tries; t++) {
        var up = solveOnce(matches, menus, target, o2, 2);
        if (!up) break;
        if (reaches(up)) { best = better(up, best); break; }
        if (best && up.obj - best.obj < 1e-4) break;
        /* a grid fine enough that this slip (just under its target) can no longer pass for one that reaches it */
        var short = Math.log(need(up.picks.length)) - Math.log(up.odds), Dn = Math.min(D / 3, 0.9 * short / (up.picks.length + 1));
        if ((o2.legs + 1) * Math.ceil(Math.log(target) / Dn) * picksN > 6e7) break;   /* keep it under about a second */
        D = Dn; o2 = Object.assign({}, o2, { grid: D });
        best = better(solveOnce(matches, menus, target, o2, false), best);
        best = better(solveOnce(matches, menus, target, o2, true), best);
      }
    }
    if (best) best = polish(best, matches, menus, opts, need);
    return best;
  }

  /* ---------- how a pick settles on a score (mirrors scudi_slips.picks); first-half picks need the half-time score ---------- */
  function settles(code, h, a, hh, ha) {
    var mk = BY_ID[code]; if (!mk) return false;
    if (mk.half) return hh == null || ha == null || hh < 0 ? null : mk.wins(hh, ha);
    return mk.wins(h, a);
  }

  /* ---------- in play: the chance a pick wins from the current score, minute and red cards (decision 87) ----------
     The live model (results/live_model.json, tools/live_fit.py; mirrored by scudi_slips/live.py): each side's goal rate in a
     minute = its pre-match expected goals x the minute's profile (slow start, faster late and in stoppage time) x the
     score-state multiplier (a side one down scores ~14% more often, two or more down ~23%; one up ~6%) x the red-card
     multipliers (a side a man short ~a third less, its opponent ~80% more), scaled so kick-off hands back the pre-match
     expected goals. Fitted on 1,136 league matches with pre-match prices (Serie A, Premier League, Ligue 1 2015-16, StatsBomb
     open data). The goals still to come are followed minute by minute as a Markov chain over the score. At kickoff it is
     the pre-match view; at full time (or half time, for a first-half pick), the result. */
  var LIVE_MODEL = {"bins":[0.7173,0.7936,0.8774,0.9064,0.8717,0.8613,0.8875,0.9012,0.9408,0.9071,0.9765,1.0392,1.0175,0.9957,1.0003,1.0225,1.0342,1.005],"stoppage":{"1":{"f":1.1903,"len":1.5},"2":{"f":1.1083,"len":4.01}},"state":{"lead1":1.0568,"lead2":0.9968,"trail1":1.1438,"trail2":1.2303},"red":{"own":0.6742,"opp":1.7823},"scale":1.0459,"fit":{"matches":1136,"goals":2952,"red_cards":303}};
  function pois(l, k) { var p = Math.exp(-l); for (var i = 1; i <= k; i++) p *= l / i; return p; }
  function liveSteps(secondHalf, minute, toHalfTime) {
    /* the minutes still to play from the clock minute shown: [bin, exposure]; bins 0-17 are the 5-minute bins of regular
       time, 18 and 19 the two stoppage periods (their average length, less what has already been played of them) */
    var M = LIVE_MODEL, out = [], k;
    minute = minute || 0;
    if (!secondHalf) {
      for (k = Math.max(0, Math.min(45, Math.floor(minute))); k < 45; k++) out.push([Math.floor(k / 5), 1]);
      out.push([18, minute < 45 ? M.stoppage['1'].len : Math.max(0.3, M.stoppage['1'].len - (minute - 45))]);
      if (toHalfTime) return out;
      minute = 45;
    }
    for (k = Math.max(45, Math.min(90, Math.floor(minute))); k < 90; k++) out.push([Math.floor(k / 5), 1]);
    out.push([19, minute < 90 ? M.stoppage['2'].len : Math.max(0.3, M.stoppage['2'].len - (minute - 90))]);
    return out;
  }
  function liveMul(diff) { var S = LIVE_MODEL.state; return diff === 0 ? 1 : diff === 1 ? S.lead1 : diff >= 2 ? S.lead2 : diff === -1 ? S.trail1 : S.trail2; }
  function liveRate(lam, bin, diff, ownRed, oppRed) {
    var M = LIVE_MODEL, f = bin >= 18 ? M.stoppage[bin === 18 ? '1' : '2'].f : M.bins[bin];
    return lam * f * liveMul(diff) * Math.pow(M.red.own, ownRed || 0) * Math.pow(M.red.opp, oppRed || 0) / 90 / (M.scale || 1);
  }
  function liveDist(lh, la, h, a, steps, rh, ra) {
    /* the chance of every (goals still to come home, away) after the steps; both sides may score in the same minute */
    var N = 11, dist = [], nd, x, y, p, diff, ph, pa, xx, yy, si;
    for (x = 0; x < N; x++) { dist.push([]); for (y = 0; y < N; y++) dist[x].push(0); }
    dist[0][0] = 1;
    for (si = 0; si < steps.length; si++) {
      var bin = steps[si][0], e = steps[si][1];
      nd = []; for (x = 0; x < N; x++) { nd.push([]); for (y = 0; y < N; y++) nd[x].push(0); }
      for (x = 0; x < N; x++) for (y = 0; y < N; y++) {
        p = dist[x][y]; if (!p) continue;
        diff = (h + x) - (a + y);
        ph = 1 - Math.exp(-liveRate(lh, bin, diff, rh, ra) * e); pa = 1 - Math.exp(-liveRate(la, bin, -diff, ra, rh) * e);
        xx = Math.min(N - 1, x + 1); yy = Math.min(N - 1, y + 1);
        nd[x][y] += p * (1 - ph) * (1 - pa); nd[xx][y] += p * ph * (1 - pa); nd[x][yy] += p * (1 - ph) * pa; nd[xx][yy] += p * ph * pa;
      }
      dist = nd;
    }
    return dist;
  }
  /* x (optional): { period, ht, rh, ra } - ESPN's period, the half-time break, red cards shown so far to the home and away side */
  var INPLAY_CACHE = new Map();
  function inplay(code, lh, la, h, a, minute, finished, hh, ha, x) {
    var mk = BY_ID[code]; if (!mk) return 0;
    var per = (x && x.period) || 0, ht = !!(x && x.ht), second = per >= 2 || ht || ((minute || 0) > 45 && per !== 1);
    var rh = (x && x.rh) || 0, ra = (x && x.ra) || 0, p = 0, i, j, dist, key, from = ht && per < 2 ? 45 : (minute || 0);
    if (mk.half) {
      if (hh != null && ha != null && hh >= 0) return mk.wins(hh, ha) ? 1 : 0;
      if (finished || second) return mk.wins(h, a) ? 1 : 0;   /* no half-time score known: the best guess left */
    } else if (finished) return mk.wins(h, a) ? 1 : 0;
    /* the same state is asked for again and again (every poll, every point of the chart): remembered */
    key = code + '|' + lh + '|' + la + '|' + h + '|' + a + '|' + from + '|' + (mk.half ? 'H' : second ? 2 : 1) + '|' + rh + '|' + ra;
    if (INPLAY_CACHE.has(key)) return INPLAY_CACHE.get(key);
    dist = mk.half ? liveDist(lh, la, h, a, liveSteps(false, from, true), rh, ra) : liveDist(lh, la, h, a, liveSteps(second, from, false), rh, ra);
    for (i = 0; i < dist.length; i++) for (j = 0; j < dist.length; j++) if (dist[i][j] && mk.wins(h + i, a + j)) p += dist[i][j];
    if (INPLAY_CACHE.size > 6000) INPLAY_CACHE.clear();
    INPLAY_CACHE.set(key, p);
    return p;
  }
  /* ---------- SNAI "sistema": every k-leg ticket from n legs (mirrors scudi_slips.sistema) ---------- */
  var SIS = { perTicket: 0.05, perSystem: 2, maxWin: 10000 };
  function elementary(xs, k) { var e = [1], j; for (j = 1; j <= k; j++) e[j] = 0; xs.forEach(function (x) { for (j = k; j >= 1; j--) e[j] += e[j - 1] * x; }); return e[k]; }
  function choose(n, k) { var c = 1; for (var i = 1; i <= k; i++) c = c * (n - k + i) / i; return Math.round(c); }
  function sistema(legs, k, stake, bonusOn) {
    var n = legs.length; if (k < 1 || k > n) return null;
    var tickets = choose(n, k), per = stake / tickets, errs = n - k, outcomes = [], profit = 0;
    var bonusK = function (os) { if (!bonusOn) return 0; var c = os.filter(function (o) { return o >= SNAI_FLOOR; }).length; return snaiBonus(c); };
    function combosOf(arr, r, cb) { var idx = []; (function rec(start, depth) { if (depth === r) { cb(idx.map(function (j) { return arr[j]; })); return; } for (var i = start; i < arr.length; i++) { idx[depth] = i; rec(i + 1, depth + 1); } })(0, 0); }
    function payout(winners) {
      if (winners.length < k) return 0;
      var os = winners.map(function (i) { return legs[i].o; });
      if (!bonusOn) return Math.min(per * elementary(os, k), SIS.maxWin * choose(winners.length, k));
      var tot = 0; combosOf(os, k, function (c) { var pr = c.reduce(function (a, b) { return a * b; }, 1); tot += Math.min(per * pr * (1 + bonusK(c)), SIS.maxWin); }); return tot;
    }
    var all = legs.map(function (_, i) { return i; });
    for (var m = 0; m <= errs; m++) {
      var tot = 0, acc = 0, lo = Infinity, hi = -Infinity;
      combosOf(all, m, function (losers) {
        var ls = {}; losers.forEach(function (i) { ls[i] = 1; });
        var pr = 1; all.forEach(function (i) { pr *= ls[i] ? 1 - legs[i].p : legs[i].p; });
        var pay = payout(all.filter(function (i) { return !ls[i]; }));
        tot += pr; acc += pr * pay; if (pay < lo) lo = pay; if (pay > hi) hi = pay; if (pay > stake) profit += pr;
      });
      outcomes.push({ losers: m, chance: tot, min: lo, max: hi, avg: tot ? acc / tot : 0 });
    }
    var any = outcomes.reduce(function (a, o) { return a + o.chance; }, 0), ev = outcomes.reduce(function (a, o) { return a + o.chance * o.avg; }, 0);
    return { n: n, k: k, tickets: tickets, perTicket: per, minStake: Math.max(SIS.perSystem, SIS.perTicket * tickets), chanceAny: any, chanceProfit: profit, avgReturn: stake ? ev / stake : 0, outcomes: outcomes };
  }

  /* ---------- reading SNAI's page when it is copied and pasted ----------
     The known matches of the week are the anchors: wherever a home name is followed closely by its away name, the prices
     that come next belong to that match. Columns default to the order SNAI shows them (1 X 2 · 1X X2 12 · U O 2.5 · GG NG);
     a header in the pasted text overrides the order of the groups. Other SNAI tabs (decision 78: Multigol, Combo,
     Handicap, 1° tempo, Segna casa/ospite, U/O casa/ospite) are read from their column headers, left to right; a column
     the reader does not know keeps its place and is skipped. A row whose numbers do not add up is flagged, not used.
     NOT VERIFIED on SNAI's real page for the new tabs: the reader follows SNAI's published market names. */
  var SNAI_COLS = ['1', 'X', '2', '1X', 'X2', '12', 'U25', 'O25', 'GG', 'NG'];
  function fold(s) { return String(s || '').normalize('NFKD').replace(/[̀-ͯ]/g, '').toLowerCase().replace(/[^a-z0-9.,:\/\-– \n]/g, ' ').replace(/[ \t]+/g, ' '); }
  function foldH(s) { return String(s || '').normalize('NFKD').replace(/[̀-ͯ]/g, '').toLowerCase().replace(/[^a-z0-9.,:\/\-–+()° \n]/g, ' ').replace(/[ \t]+/g, ' '); }
  function firstAt(t, re) { var m = re.exec(t); return m ? m.index : -1; }
  function columnsFrom(text) {
    var t = ' ' + fold(text).replace(/\n/g, ' ') + ' ';
    var under = firstAt(t, /\s(under|u)\s/), over = firstAt(t, /\s(over|o)\s/);
    var ng = firstAt(t, /\s(no ?goal|ng)\s/), gg = firstAt(t, /\s(goal|gg)\s/);
    var groups = [
      { ids: ['1', 'X', '2'], at: firstAt(t, /\s1\s+x\s+2\s/) },
      { ids: ['1X', 'X2', '12'], at: firstAt(t, /\s1x\s+x2\s+12\s/) },
      { ids: over > -1 && (under < 0 || over < under) ? ['O25', 'U25'] : ['U25', 'O25'], at: under < 0 ? over : over < 0 ? under : Math.min(under, over) },
      { ids: ng > -1 && (gg < 0 || ng < gg) ? ['NG', 'GG'] : ['GG', 'NG'], at: gg < 0 ? ng : ng < 0 ? gg : Math.min(gg, ng) }];
    if (groups.filter(function (g) { return g.at > -1; }).length < 3) return SNAI_COLS.slice();
    return groups.map(function (g, i) { return { g: g, at: g.at < 0 ? 1e9 + i : g.at }; }).sort(function (a, b) { return a.at - b.at; }).reduce(function (acc, x) { return acc.concat(x.g.ids); }, []);
  }
  /* the columns of one of SNAI's other tabs, from the header text above the first match (null: not such a tab) */
  var MAINSET = { '1': 1, 'X': 1, '2': 1, '1X': 1, 'X2': 1, '12': 1, 'U25': 1, 'O25': 1, 'GG': 1, 'NG': 1 };
  function columnsExt(zone) {
    var z = ' ' + foldH(zone).replace(/\n/g, ' ') + ' ';
    z = z.replace(/\((\d)\s*:\s*(\d)\)/g, function (_m, a, b) { var l = (+a) - (+b); return ' hl' + (l >= 0 ? '+' : '') + l + ' '; })
      .replace(/\(\s*([+-])\s*(\d)\s*\)/g, ' hl$1$2 ')
      .replace(/multi ?go(a)?l/g, ' mg ').replace(/primo tempo|1\s*°\s*t(empo)?\b|\b1\s*tempo\b|\b1t\b|\bpt\b/g, ' ht ')
      .replace(/secondo tempo|2\s*°\s*t(empo)?\b|\b2\s*tempo\b|\b2t\b|\bst\b/g, ' sh ').replace(/\bfinale\b|\bft\b|\bfinal\b/g, ' ft ')
      .replace(/handicap|\bhand\b|\bhcp\b/g, ' hcp ').replace(/\bno ?goal\b|\bno ?gol\b/g, ' ng ').replace(/\bgoal\b|\bgol\b/g, ' gg ')
      .replace(/\bunder\b/g, ' u ').replace(/\bover\b/g, ' o ').replace(/\bospite\b|\baway\b|\btrasferta\b/g, ' away ').replace(/\bcasa\b|\bhome\b/g, ' home ')
      .replace(/\b([uo])\s*([0-4])[.,]5\b/g, ' $1$2.5 ').replace(/\+/g, ' + ').replace(/7 \+/g, '7+').replace(/\s+/g, ' ');
    var tk = z.trim().split(' '), cols = [], st = { mode: '', half: false, team: '', line: null }, pend = null, ext = false, i;
    var lineAt = function (j) { for (var d = 1; d <= 2; d++) { var x = tk[j + d] || '', y = tk[j - d] || ''; if (/^[0-4][.,]5$/.test(x)) return x.charAt(0); if (/^[0-4][.,]5$/.test(y)) return y.charAt(0); } return '2'; };
    function emit(code) {
      if (pend !== null) { var c = pend + '+' + code; pend = null; cols.push(BY_ID[c] ? c : '?'); ext = true; return; }
      cols.push(code);
    }
    for (i = 0; i < tk.length; i++) {
      var w = tk[i], m;
      if (w === 'ht') { st.half = true; ext = true; continue; }
      if (w === 'sh') { st.half = 'second'; ext = true; continue; }
      if (w === 'ft') { st.half = false; continue; }
      if (w === 'mg') { st.mode = 'mg'; ext = true; continue; }
      if (w === 'hcp') { st.mode = 'hcp'; ext = true; continue; }
      if (w === 'segna') { st.mode = 'segna'; ext = true; continue; }
      if (w === 'combo') { ext = true; continue; }
      if (w === 'home' || w === 'away') { st.team = w === 'home' ? 'H' : 'A'; ext = true; continue; }
      if ((m = /^hl([+-]\d)$/.exec(w))) {
        st.line = +m[1]; st.mode = 'hcp'; ext = true;
        for (var b = cols.length - 1; b >= 0 && /^[1X2]H\?$/.test(cols[b]); b--) cols[b] = BY_ID[cols[b].charAt(0) + 'H' + (st.line >= 0 ? '+' : '') + st.line] ? cols[b].charAt(0) + 'H' + (st.line >= 0 ? '+' : '') + st.line : '?';
        continue;
      }
      if (w === '+') { if (cols.length) pend = cols.pop(); continue; }
      if (st.half === 'second') { if (/^(1|x|2|1x|x2|12|gg|ng|[uo][0-4]\.5|[0-7]-[0-7])$/.test(w)) cols.push('?'); continue; }
      if (/^(1|x|2|1x|x2|12)$/.test(w)) {
        var base = w.toUpperCase();
        if (st.mode === 'hcp' && pend === null) { cols.push(st.line == null ? base + 'H?' : (BY_ID[base + 'H' + (st.line >= 0 ? '+' : '') + st.line] ? base + 'H' + (st.line >= 0 ? '+' : '') + st.line : '?')); continue; }
        emit(st.half ? (BY_ID['1T' + base] ? '1T' + base : '?') : base); continue;
      }
      if ((m = /^([uo])([0-4])\.5$/.exec(w)) || /^[uo]$/.test(w)) {
        var uo = m ? m[1].toUpperCase() : w.toUpperCase(), n = m ? m[2] : lineAt(i), code = uo + n + '5';
        if (st.half) code = '1T' + code; else if (st.team && pend === null) code = st.team + code;
        emit(BY_ID[code] ? code : '?'); continue;
      }
      if (w === 'gg' || w === 'ng') { emit(st.half ? (w === 'gg' ? '1TGG' : '1TNG') : w.toUpperCase()); continue; }
      if (w === 'si' || w === 'no') { if (st.mode === 'segna' && st.team) cols.push(st.team + (w === 'si' ? 'O05' : 'U05')); continue; }
      if ((m = /^([0-7])-([0-7])$/.exec(w))) {
        var mg = (st.team && pend === null ? st.team : '') + 'MG' + m[1] + '-' + m[2];
        emit(st.half ? '?' : BY_ID[mg] ? mg : '?'); continue;
      }
      if (w === '7+') { cols.push('?'); continue; }
    }
    cols = cols.map(function (c) { return /H\?$/.test(c) ? '?' : c; });
    var known = cols.filter(function (c) { return c !== '?'; });
    if (!ext || known.length < 1 || cols.length < 2 || known.every(function (c) { return MAINSET[c]; })) return null;
    return cols;
  }
  function plausible(pr) {
    var ok = function (ids, lo, hi) { if (!ids.every(function (i) { return pr[i] > 1; })) return true; var s = ids.reduce(function (a, i) { return a + 1 / pr[i]; }, 0); return s > lo && s < hi; };
    return ok(['1', 'X', '2'], 1.01, 1.13) && ok(['U25', 'O25'], 1.01, 1.13) && ok(['GG', 'NG'], 1.01, 1.13) && ok(['1T1', '1TX', '1T2'], 1.0, 1.3) && ok(['1TU15', '1TO15'], 1.0, 1.25) &&
      (!(pr['1'] && pr['X'] && pr['1X']) || pr['1X'] < Math.min(pr['1'], pr['X'])) && (!(pr['2'] && pr['X'] && pr['X2']) || pr['X2'] < Math.min(pr['2'], pr['X']));
  }
  function anchors(t, matches, f) {
    var hits = [];
    matches.forEach(function (m) {
      var best = null;
      (m.names || [[m.home], [m.away]])[0].forEach(function (h) {
        h = f(h).trim(); if (h.length < 3) return;
        for (var i = t.indexOf(h); i > -1; i = t.indexOf(h, i + 1)) {
          if (i > 0 && /[a-z]/.test(t[i - 1])) continue;
          (m.names || [[m.home], [m.away]])[1].forEach(function (a) {
            a = f(a).trim(); if (a.length < 3) return;
            var j = t.indexOf(a, i + h.length);
            if (j > -1 && j - (i + h.length) <= 40 && !/[a-z]/.test(t[j + a.length] || ' ') && (!best || i < best.i)) best = { i: i, end: j + a.length };
          });
        }
      });
      if (best) hits.push({ match: m, i: best.i, end: best.end });
    });
    hits.sort(function (x, y) { return x.i - y.i; });
    return hits.filter(function (h, n) { return !n || h.i >= hits[n - 1].end; });
  }
  /* the header rows right above the first match: read upwards from the match, skipping date and time lines, keeping lines
     made only of column labels and tab names, and stopping at the first line of other words (a breadcrumb, a tab bar,
     the site's menus), so text further up the page never changes the columns */
  var HEAD_WORDS = {}, DAYMON = {};
  ('x 1x x2 gg ng goal gol no si u o under over multigol multigoal multi combo handicap hand hcp tempo primo secondo 1° 2° 1t 2t pt st ' +
    'casa ospite home away trasferta segna finale ft final esito e').split(' ').forEach(function (w) { HEAD_WORDS[w] = 1; });
  ('lun mar mer gio ven sab dom gen feb apr mag giu lug ago set ott nov dic oggi domani lunedi martedi mercoledi giovedi venerdi sabato domenica ' +
    'gennaio febbraio marzo aprile maggio giugno luglio agosto settembre ottobre novembre dicembre').split(' ').forEach(function (w) { DAYMON[w] = 1; });
  var LABEL_TOK = /^(1|x|2|1x|x2|12|gg|ng|u|o|[uo]\d[.,]5|\d[.,]5|[0-7]-[0-7]|7\+|\+)$/;
  function headerOf(zone) {
    var lines = zone.split('\n'); lines.pop();                  /* what stands before the match's name on its own line: a time, a code */
    var out = [], skipped = 0;
    for (var i = lines.length - 1; i >= 0; i--) {
      var l = lines[i].trim(); if (!l) continue;
      var toks = l.split(/[\s\/()]+/).filter(Boolean), words = toks.filter(function (w) { return /[a-z]/.test(w); });
      if (words.every(function (w) { return DAYMON[w]; }) && !toks.some(function (w) { return LABEL_TOK.test(w); })) continue;   /* a date or a time */
      var mine = words.every(function (w) { return HEAD_WORDS[w]; }), labels = toks.some(function (w) { return LABEL_TOK.test(w); });
      if (mine) { out.unshift(l); continue; }
      if (!out.length && labels) { out.unshift(l); break; }       /* a header row with a few words of its own ("Esito finale 1 X 2") */
      if (!out.length && skipped < 3) { skipped++; continue; }     /* the competition's name between the header and the first match */
      break;
    }
    return out.join('\n');
  }
  /* which columns a pasted text carries: another tab's header right above the first match, else the main groups */
  function columnsOf(text, matches) {
    var tH = foldH(text), first = anchors(tH, matches || [], foldH)[0];
    if (!first) return columnsExt(tH) || columnsFrom(text);
    var zone = tH.slice(0, first.i), head = headerOf(zone);
    if (!head) return columnsExt(zone) || columnsFrom(text);
    var h1 = ' ' + head.replace(/\n/g, ' ') + ' ', main = /\s1\s+x\s+2\s/.test(h1) && /\s1x\s+x2\s+12\s/.test(h1);
    var modes = (h1.match(/multi ?go(a)?l|combo|handicap|tempo|casa|ospite|segna/g) || []).filter(function (w, i, a) { return a.indexOf(w) === i; }).length;
    var ext = columnsExt(head);
    if (ext && !(main && modes > 1)) return ext;                   /* several tab names over a main header: a tab bar, not a tab */
    return main ? columnsFrom(head) : ext || columnsFrom(text);
  }
  /* the prices read before the goals line when some were closed: 1 X 2 are taken as read, and the double chances are
     placed where they agree best with those three (a closed price is left empty) */
  function fitClosed(nums, cols, uoAt) {
    var head = cols.slice(0, uoAt), miss = uoAt - nums.length, empty = head.map(function () { return null; });
    var dcAt = head.map(function (c, i) { return c === '1X' || c === 'X2' || c === '12' ? i : -1; }).filter(function (i) { return i > -1; });
    if (head[0] !== '1' || head[1] !== 'X' || head[2] !== '2' || nums.length < 3 || miss > dcAt.length || nums.slice(0, 3).some(function (v) { return !(v > 1); })) return empty;
    var q = nums.slice(0, 3).map(function (o) { return 1 / o; }), s = q[0] + q[1] + q[2]; q = q.map(function (v) { return v / s; });
    var fair = { '1X': q[0] + q[1], 'X2': q[1] + q[2], '12': q[0] + q[2] }, best = null;
    (function pick(from, chosen) {
      if (chosen.length === miss) {
        var out = [], k = 0, score = 0;
        head.forEach(function (c, i) { if (chosen.indexOf(i) > -1) out.push(null); else { var v = nums[k++]; out.push(v); if (fair[c] && v > 1) score += Math.abs(Math.log(v * fair[c]) + 0.05); } });
        if (!best || score < best.score) best = { score: score, out: out };
        return;
      }
      for (var j = from; j < dcAt.length; j++) pick(j + 1, chosen.concat([dcAt[j]]));
    })(0, []);
    return best ? best.out : empty;
  }
  function parseSnai(text, matches) {
    var t = fold(text), cols = columnsOf(text, matches), main = cols.every(function (c) { return MAINSET[c]; }), hits = anchors(t, matches, fold);
    var uoAt = main ? cols.reduce(function (a, c, i) { return a < 0 && (c === 'U25' || c === 'O25') ? i : a; }, -1) : -1;
    return hits.map(function (h, n) {
      var seg = t.slice(h.end, n + 1 < hits.length ? hits[n + 1].i : t.length), nums = [], re = /(^|[\s:])(\d{1,3}[.,]\d{1,2}|[-–])(?=\s|$)/g, x;
      var rowCols = cols.slice(), line = null;
      while ((x = re.exec(seg))) {
        var tok = x[2];
        if (x[1] === ':') continue;                                     /* a kick-off time */
        if (/^[-–]$/.test(tok)) { nums.push(null); continue; }
        /* the goals line printed between the columns (SNAI's 2.5 selector); a closed price (a padlock on SNAI) prints
           nothing, so when the line comes early the prices read so far are put back where they fit */
        if (main && line === null && /^\d[.,]5$/.test(tok) && (uoAt > -1 ? nums.length <= uoAt + 1 : nums.length >= 6 && nums.length <= 7)) {
          line = tok.charAt(0);
          if (uoAt > -1 && nums.length < uoAt) nums = fitClosed(nums, cols, uoAt);
          if (line !== '2') rowCols = rowCols.map(function (c) { if (c !== 'U25' && c !== 'O25') return c; var k = c.charAt(0) + line + '5'; return BY_ID[k] ? k : '?'; });
          continue;
        }
        nums.push(parseFloat(tok.replace(',', '.')));
        if (nums.length >= cols.length) break;
      }
      var prices = {}; rowCols.forEach(function (c, i) { if (c !== '?' && nums[i] != null && nums[i] > 1) prices[c] = nums[i]; });
      var chk = checkPrices(prices, h.match.ref || h.match), got = Object.keys(prices).length;
      return { match: h.match, prices: prices, count: got, odd: chk.odd, ok: chk.ok && (main ? got >= 3 && prices['1'] && prices['X'] && prices['2'] : got >= 1), main: main };
    });
  }
  /* a price far from the market's own chance (more than 20% above fair, or under 60% of it) is a column read wrong, not a
     gift: it is taken out of `prices` (in place) and listed in `odd`; ok when the rest adds up and most prices were kept */
  function checkPrices(prices, ref, exact) {
    /* exact: prices read from SNAI's own page, not from a picture; the market's chances may be a day old, so only a
       price twice the fair one or under 40% of it counts as a button read wrong */
    var ch = (ref.pre && ref.pre.chances) || (ref.lh > 0 && ref.la > 0) ? chancesOf(ref) : null, odd = [], hi = exact ? 2 : 1.2, lo = exact ? 0.4 : 0.6;
    if (ch) Object.keys(prices).forEach(function (c) { var p = ch[c]; if (p > 0 && p < 1 && (prices[c] * p > hi || prices[c] * p < lo)) { odd.push(c); delete prices[c]; } });
    var got = Object.keys(prices).length;
    return { prices: prices, odd: odd, ok: plausible(prices) && odd.length <= got };
  }

  /* ---------- SNAI's own page, read in the browser (decision 83) ----------
     The reader started from the bookmark on snai.it sends each row as SNAI draws it: SNAI's event number, the two names,
     the kick-off as printed ("25/09 17:00"), the competition, and every price button as [market, line, outcome, price].
     The codes are SNAI's own, from the buttons' esito_<palinsesto>_<event>_<market>_<line>_<outcome>: market 3 is the
     final result 1X2, 28319 the double chance, 7989 under/over with the goals line in hundredths (250 = 2.5), 18 goal/no
     goal. A padlocked button comes with no price. Codes Scudi does not know are ignored, so the reader can stay as it is
     while Scudi learns more of them. */
  var SNAI_CODES = { 3: { 1: '1', 2: 'X', 3: '2' }, 28319: { 1: '1X', 3: 'X2', 2: '12' }, 18: { 1: 'GG', 2: 'NG' } };
  function snaiMarkets(list) {
    var prices = {}, locked = [], shot = {}, line = null;
    (list || []).forEach(function (x) {
      var mk = x[0], ln = x[1], oc = x[2], pr = x[3], id = null, sk = null;
      if (SNAI_CODES[mk]) { id = SNAI_CODES[mk][oc] || null; sk = id; }
      else if (mk === 7989 && ln > 0 && ln % 50 === 0 && ln % 100 !== 0 && (oc === 1 || oc === 2)) {
        id = (oc === 1 ? 'U' : 'O') + (ln - 50) / 100 + '5'; if (!BY_ID[id]) id = null;
        if (ln === 250) sk = oc === 1 ? 'U' : 'O';
        if (line === null || ln === 250) line = String((ln - 50) / 100);
      }
      if (!id) { if (sk) shot[sk] = pr > 1 ? pr : undefined; return; }
      if (pr > 1 && pr < 1000) { prices[id] = pr; if (sk) shot[sk] = pr; }
      else if (locked.indexOf(id) < 0) locked.push(id);
    });
    Object.keys(shot).forEach(function (k) { if (shot[k] === undefined) delete shot[k]; });
    return { prices: prices, locked: locked, shot: shot, line: line };
  }
  /* "25/09 17:00" (or "25/09/2026 17:00", or a time alone): day, month, hour and minute, in the reading device's time.
     On snai.it the hour, the colon and the minutes are separate pieces of text: "25/09 17 : 00" */
  function snaiWhen(txt) {
    var s = String(txt || ''), d = /(\d{1,2})\/(\d{1,2})(?:\/\d{2,4})?/.exec(s), t = /(\d{1,2})\s*[:.]\s*(\d{2})(?!\d)/.exec(s.replace(d ? d[0] : '', ' '));
    if (!d && !t) return null;
    var out = {};
    if (d && +d[1] >= 1 && +d[1] <= 31 && +d[2] >= 1 && +d[2] <= 12) { out.d = +d[1]; out.mo = +d[2]; }
    if (t && +t[1] < 24 && +t[2] < 60) { out.hh = +t[1]; out.mi = +t[2]; }
    return out.d != null || out.hh != null ? out : null;
  }
  /* a message from the reader, checked field by field: anything malformed is dropped, sizes are capped */
  function snaiRows(msg) {
    if (!msg || typeof msg !== 'object' || msg.type !== 'scudi-snai' || !Array.isArray(msg.rows)) return null;
    var str = function (v, n) { return typeof v === 'string' ? v.replace(/\s+/g, ' ').trim().slice(0, n) : ''; }, out = [];
    msg.rows.slice(0, 800).forEach(function (r) {
      if (!r || typeof r !== 'object') return;
      var id = String(r.id == null ? '' : r.id).replace(/[^0-9A-Za-z_-]/g, '').slice(0, 24), home = str(r.home, 60), away = str(r.away, 60);
      if (!id || !home || !away || !Array.isArray(r.m)) return;
      var m = [];
      r.m.slice(0, 120).forEach(function (x) {
        if (!Array.isArray(x) || x.length < 3) return;
        var a = [+x[0], +x[1], +x[2], x[3] == null ? null : +x[3]];
        if (a.slice(0, 3).every(function (v) { return isFinite(v) && Math.floor(v) === v && Math.abs(v) < 1e7; }) && (a[3] === null || (isFinite(a[3]) && a[3] > 0))) m.push(a);
      });
      out.push({ id: id, home: home, away: away, when: str(r.when, 40), comp: str(r.comp, 80), m: m });
    });
    return out;
  }

  /* ---------- live: one match as ESPN reports it, and a slip's story rebuilt from its goals (decision 80) ----------
     ESPN lists each goal with its minute. Shoot-out kicks are not goals; an own goal is tried both ways until the list adds
     up to the score. With a list that adds up, a bet is settled on regular time as SNAI does: a match that went to extra
     time counts only the goals up to 90'+stoppage. The same list rebuilds the slip's chance at every past minute, so the
     chart is complete even for the minutes the page was closed. */
  var LIVE_END = 115;
  var ET_STATUS = /^STATUS_(FINAL_AET|FINAL_PEN|END_OF_REGULATION|END_OF_EXTRATIME|HALFTIME_ET|OVERTIME|SHOOTOUT|(FIRST_HALF_|SECOND_HALF_)?EXTRA_?TIME)$/i;   /* minutes from kick-off to the final whistle: first half 0-48, break 48-63, second half to 108, stoppage */
  function goalClock(s) { s = String(s || ''); var m = parseInt(s.split("'")[0], 10), x = parseInt(s.split('+')[1] || '0', 10) || 0; return isNaN(m) ? null : { m: m, x: x, d: s }; }
  function goalWall(g) { return g.m <= 45 ? g.m + Math.min(g.x, 2.9) : 63 + (g.m - 45) + Math.min(g.x, 6.9); }
  function clockAt(e) { return e < 45 ? Math.max(0, e) : e < 63 ? Math.min(48, e) : Math.min(96, 45 + (e - 63)); }
  function countSide(gs, s) { var n = 0; for (var i = 0; i < gs.length; i++) if (gs[i].s === s) n++; return n; }
  function espnState(leg, ev, now) {
    if (!ev) return { state: new Date(leg.kick).getTime() > (now || Date.now()) ? 'pre' : 'unknown' };
    var comp = (ev.competitions || [])[0] || {}, st = (comp.status || ev.status || {}), ty = st.type || {}, cs = comp.competitors || [];
    var home = cs.filter(function (c) { return c.homeAway === 'home'; })[0], away = cs.filter(function (c) { return c.homeAway === 'away'; })[0];
    if (!home || !away) return { state: 'unknown' };
    var swap = leg.th != null && String((home.team || {}).id) === String(leg.ta);
    var H0 = +home.score || 0, A0 = +away.score || 0, period = +st.period || 0;
    var ck = goalClock(st.displayClock), minute = ck ? ck.m + ((ck.m === 45 && period <= 1) || ck.m >= 90 ? ck.x : 0) : (ty.state === 'in' ? (period === 2 ? 60 : 20) : 0);
    /* ESPN's status reads "First Half" and "Second Half" while the ball is in play: only the break itself is half time */
    var isHT = ty.name === 'STATUS_HALFTIME' || /^(ht|half-?time)$/i.test(String(ty.shortDetail || ty.description || '').trim());
    if (isHT) minute = 45;
    /* over only when ESPN says completed: a postponed, cancelled or suspended match is "post" without being played out */
    var state = ty.completed ? 'post' : ty.state === 'in' ? 'in' : ty.state === 'post' ? 'unknown' : 'pre';
    var et = period > 2 || ET_STATUS.test(String(ty.name || ''));
    var side = {}, list = (comp.details || []).filter(function (d) { return d.scoringPlay && !d.shootout; }), goals = null;
    cs.forEach(function (c) { side[String((c.team || {}).id)] = c.homeAway; });
    if (state !== 'pre') [false, true].some(function (flip) {
      var out = [], th = 0, ta = 0, ok = true;
      list.forEach(function (d) {
        var sd = side[String((d.team || {}).id)], g = goalClock((d.clock || {}).displayValue);
        if (!sd || !g) { ok = false; return; }
        if (flip && d.ownGoal) sd = sd === 'home' ? 'away' : 'home';
        if (sd === 'home') th++; else ta++;
        g.s = (sd === 'home') !== swap ? 'h' : 'a'; out.push(g);
      });
      if (ok && th === H0 && ta === A0) { goals = out; return true; }
      return false;
    });
    var h = swap ? A0 : H0, a = swap ? H0 : A0, hh = null, ha = null;
    /* players sent off so far (ESPN flags them in the match details), counted for the leg's home and away side, with the minute */
    var reds = [], rh = 0, ra = 0;
    (comp.details || []).forEach(function (d) {
      if (!d.redCard) return;
      var sd = side[String((d.team || {}).id)]; if (!sd) return;
      var mine = (sd === 'home') !== swap, g = goalClock((d.clock || {}).displayValue);
      if (mine) rh++; else ra++;
      reds.push({ s: mine ? 'h' : 'a', m: g ? g.m : null });
    });
    /* after extra time without a goal list that adds up, the 90-minute score cannot be told: left open, never settled on
       the score after extra time */
    if (et && !goals) return { state: 'unknown', et: true, h: h, a: a, minute: 90, period: period, detail: ty.shortDetail || '', hh: null, ha: null, goals: null, date: ev.date, rh: rh, ra: ra, reds: reds };
    if (goals) {
      if (et) {
        goals = goals.filter(function (g) { return g.m <= 90; });   /* extra-time goals do not count for the bet */
        state = 'post'; minute = 90;                                 /* the 90 minutes are over: the bet is decided */
      }
      h = countSide(goals, 'h'); a = countSide(goals, 'a');
      if (state === 'post' || (state === 'in' && (minute > 45 || period >= 2 || isHT))) {
        var first = goals.filter(function (g) { return g.m <= 45; }); hh = countSide(first, 'h'); ha = countSide(first, 'a');
      }
    }
    return { state: state, h: h, a: a, minute: minute, period: period, ht: isHT, detail: ty.shortDetail || '', hh: hh, ha: ha, goals: goals, et: et, date: ev.date, rh: rh, ra: ra, reds: reds };
  }
  /* one leg now: its live chance, whether it is winning, whether it is decided (a first-half pick is decided at half time) */
  function legLive(leg, st) {
    var mk = BY_ID[leg.code], half = !!(mk && mk.half), res = null, done = false;
    if (half ? st.hh != null : st.state === 'post') { res = settles(leg.code, st.h, st.a, st.hh, st.ha); done = res != null; }
    var p = done ? (res ? 1 : 0) : st.state === 'in' || st.state === 'post' ? inplay(leg.code, leg.lh || 1.3, leg.la || 1.1, st.h, st.a, st.minute, st.state === 'post' && !half, st.hh, st.ha, { period: st.period, ht: st.ht, rh: st.rh, ra: st.ra }) : leg.p;
    /* the in-play model follows the expected goals through the match; the pick's own chance (market, Dixon-Coles, calibration)
       knows more about this match. Their gap at kick-off is carried on the logit scale and fades with the time left, so the
       line does not jump at the first whistle and the score takes over as the match runs out. */
    if (!done && (st.state === 'in' || st.state === 'post') && leg.p > 0 && leg.p < 1 && p > 0 && p < 1) {
      var q0 = inplay(leg.code, leg.lh || 1.3, leg.la || 1.1, 0, 0, 0, false), span = half ? 47 : 93, left = Math.max(0, Math.min(1, (span - (st.minute || 0)) / span));
      if (q0 > 0 && q0 < 1) p = sigmoid(logit(p) + (logit(leg.p) - logit(q0)) * left);
    }
    var now = st.state === 'pre' || st.state === 'unknown' ? null : done ? res : half ? (mk ? mk.wins(st.h, st.a) : null) : settles(leg.code, st.h, st.a);
    return { p: p, now: now, done: done };
  }
  /* how late a match in play is running: minutes since its kick-off time against its clock (a late start, a long break) */
  function lateBy(st, e) {
    if (!st || st.state !== 'in') return null;
    var m = st.minute || 0, second = (st.period || 0) >= 2 || (m > 45 && !st.ht);
    if (st.ht || m >= 90 || (!second && m >= 45)) return null;   /* the clock stands still at the break and in stoppage time */
    return Math.max(-5, Math.min(30, second ? e - (63 + m - 45) : e - m));
  }
  /* one leg e minutes after its (actual) kick-off, rebuilt from its goal list; st is how it stands now. Each goal counts from
     g.e (its moment, set by story) or else from its clock. */
  function stateAt(st, e) {
    if (e < 0) return { state: 'pre' };
    if (st.state === 'post' && e >= LIVE_END) return st;
    var gs = st.goals.filter(function (g) { return (g.e != null ? g.e : goalWall(g)) <= e + 1e-9; }), m = clockAt(e);
    if (st.state === 'in') m = Math.min(m, st.minute || 0);
    var inBreak = e >= 48 && e < 63;
    var htDone = e >= 48 && !(st.state === 'in' && st.hh == null), first = htDone ? st.goals.filter(function (g) { return g.m <= 45; }) : null;
    var rs = (st.reds || []).filter(function (r) { return r.m != null && r.m <= m; });
    return { state: 'in', minute: inBreak ? 45 : m, h: countSide(gs, 'h'), a: countSide(gs, 'a'), hh: first ? countSide(first, 'h') : null, ha: first ? countSide(first, 'a') : null,
      period: e >= 63 ? 2 : 1, ht: inBreak, rh: rs.filter(function (r) { return r.s === 'h'; }).length, ra: rs.filter(function (r) { return r.s === 'a'; }).length };
  }
  /* the slip's chance at every past minute and the goals that moved it. offs[i]: minutes from the first kick-off to leg i's
     actual start; nowT: minutes from the first kick-off to now. null when a started leg has no goal list that adds up.
     Every goal gets its own moment (two goals in the same minute of different matches each show their own effect), and
     none is later than now (a goal read in the minute it was scored already counts). */
  function story(legs, states, offs, nowT) {
    if (!states.every(function (s) { return s.state === 'pre' || s.state === 'unknown' || s.goals; })) return null;
    var all = [], sts = states.map(function (st, i) {
      if (!st.goals) return st;
      var gl = st.goals.map(function (g) { var c = Object.assign({}, g); c.w = Math.min(offs[i] + goalWall(g), nowT - 0.05); c.i = i; all.push(c); return c; });
      return Object.assign({}, st, { goals: gl });
    });
    all.sort(function (a, b) { return a.w - b.w || a.i - b.i; });
    all.forEach(function (g, j) { if (j && g.w < all[j - 1].w + 1e-3) g.w = all[j - 1].w + 1e-3; g.e = g.w - offs[g.i]; });
    var legP = function (i, T) { var st = sts[i]; return st.state === 'pre' || st.state === 'unknown' ? legs[i].p : legLive(legs[i], stateAt(st, T - offs[i])).p; };
    var at = function (T) { var p = 1; for (var i = 0; i < legs.length; i++) p *= legP(i, T); return p; };
    var ts = [0];
    legs.forEach(function (l, i) {
      if (!sts[i].goals) return;
      for (var e = 0; e <= LIVE_END; e += 2) ts.push(offs[i] + e);
      ts.push(offs[i] + 48, offs[i] + LIVE_END);
    });
    all.forEach(function (g) { ts.push(g.w - 5e-4, g.w); });
    ts = ts.filter(function (t) { return t >= 0 && t < nowT - 1e-6; }).sort(function (a, b) { return a - b; }).filter(function (t, j, a) { return !j || t - a[j - 1] > 1e-5; });
    var pts = ts.map(function (t) { return { t: t, p: at(t) }; });
    pts.push({ t: nowT, p: legs.reduce(function (a, l, i) { return a * legLive(l, states[i]).p; }, 1) });
    var ev = [];
    all.forEach(function (g) {
      var before = at(g.w - 5e-4), after = at(g.w); if (!(before > 0)) return;
      var s = stateAt(sts[g.i], g.e);
      ev.unshift({ t: g.w, m: g.m, md: g.d, i: g.i, h: s.h, a: s.a, before: before, after: after });
    });
    return { pts: pts, ev: ev };
  }

  return { matrix: matrix, half: half, chancesOf: chancesOf, candidates: candidates, menuFor: menuFor, prune: prune, solve: solve, MARKETS: MARKETS, BY_ID: BY_ID, GROUPS: GROUPS, OFFERED: OFFERED,
    CLASSIC_IDS: CLASSIC_IDS, NOT_OFFERED: NOT_OFFERED, NEW_FLOOR: NEW_FLOOR, ASSUMED: ASSUMED, assumedPrice: assumedPrice, spreadOf: spreadOf, learnedP: learnedP, logit: logit, sigmoid: sigmoid,
    snaiBonus: snaiBonus, haircutFrom: haircutFrom, ratiosFrom: ratiosFrom, price: price, SNAI_FLOOR: SNAI_FLOOR, HALF_SHARE: HALF_SHARE, HALF_RHO: HALF_RHO,
    settles: settles, inplay: inplay, LIVE_MODEL: LIVE_MODEL, liveRate: liveRate, liveSteps: liveSteps, liveDist: liveDist, espnState: espnState, legLive: legLive, stateAt: stateAt, story: story, lateBy: lateBy, goalWall: goalWall, LIVE_END: LIVE_END, sistema: sistema, SIS: SIS, parseSnai: parseSnai, columnsFrom: columnsFrom, columnsOf: columnsOf, SNAI_COLS: SNAI_COLS,
    checkPrices: checkPrices, plausible: plausible, snaiMarkets: snaiMarkets, snaiWhen: snaiWhen, snaiRows: snaiRows, SNAI_CODES: SNAI_CODES };
})();

  var CLUB_WORDS = /\b(fc|ac|as|ss|us|cf|sc|afc|ssc|club|calcio|de|1909|1913|cfc|bc|fk|sv|vfb|vfl|tsg|sk|rc|og|ol|sco|sd|ud|ca|cd|rcd)\b/g;
  function tkey(name) { return String(name || '').normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9 ]+/g, ' ').replace(CLUB_WORDS, ' ').replace(/\s+/g, ' ').trim(); }
  /* the odds feed's short names against ESPN's display names */
  var ALIASES = { 'inter': 'internazionale', 'inter milan': 'internazionale', 'milan': 'ac milan', 'man city': 'manchester city', 'man united': 'manchester united', 'man utd': 'manchester united',
    'psg': 'paris saint germain', 'bayern': 'bayern munich', 'atletico': 'atletico madrid', 'athletic': 'athletic club', 'athletic bilbao': 'athletic club', 'betis': 'real betis', 'celta': 'celta vigo',
    'gladbach': 'borussia monchengladbach', 'dortmund': 'borussia dortmund', 'leverkusen': 'bayer leverkusen', 'leipzig': 'rb leipzig', 'frankfurt': 'eintracht frankfurt', 'werder': 'werder bremen',
    'shakhtar': 'shakhtar donetsk', 'bodo glimt': 'bodo glimt', 'tottenham': 'tottenham hotspur', 'spurs': 'tottenham hotspur', 'brighton': 'brighton hove albion', 'wolves': 'wolverhampton wanderers',
    'newcastle': 'newcastle united', 'west ham': 'west ham united', 'forest': 'nottingham forest', 'sporting': 'sporting cp', 'sporting lisbon': 'sporting cp', 'porto': 'fc porto', 'psv': 'psv eindhoven',
    'juve': 'juventus', 'verona': 'hellas verona', 'hellas verona': 'hellas verona', 'atalanta': 'atalanta', 'roma': 'roma', 'lazio': 'lazio', 'napoli': 'napoli', 'fenerbahce': 'fenerbahce', 'galatasaray': 'galatasaray',
    /* national teams: the odds feed's spelling against ESPN's */
    'czech republic': 'czechia', 'turkey': 'turkiye', 'ireland': 'republic of ireland', 'bosnia and herzegovina': 'bosnia herzegovina', 'bosnia': 'bosnia herzegovina',
    'korea republic': 'south korea', 'usa': 'united states', 'cote d ivoire': 'ivory coast', 'macedonia': 'north macedonia', 'holland': 'netherlands' };

  var REG = [['Serie A', 'core', 'ita.1'], ['Premier League', 'core', 'eng.1'], ['La Liga', 'core', 'esp.1'], ['Bundesliga', 'core', 'ger.1'], ['Ligue 1', 'core', 'fra.1'],
    ['Champions League', 'core', 'uefa.champions'], ['Nations League', 'national', 'uefa.nations'], ['World Cup qualifiers', 'national', 'fifa.worldq.uefa'], ['Euro qualifiers', 'national', 'uefa.euroq'],
    ['World Cup', 'national', 'fifa.world'], ['Euro', 'national', 'uefa.euro'], ['Europa League', 'cups', 'uefa.europa'], ['Conference League', 'cups', 'uefa.europa.conf'],
    ['Serie B', 'second', 'ita.2'], ['Championship', 'second', 'eng.2'], ['League One', 'second', 'eng.3'], ['La Liga 2', 'second', 'esp.2'], ['2. Bundesliga', 'second', 'ger.2'], ['Ligue 2', 'second', 'fra.2'],
    ['Eredivisie', 'europe', 'ned.1'], ['Primeira Liga', 'europe', 'por.1'], ['Belgian Pro League', 'europe', 'bel.1'], ['Süper Lig', 'europe', 'tur.1'], ['Scottish Premiership', 'europe', 'sco.1'],
    ['Austrian Bundesliga', 'europe', 'aut.1'], ['Swiss Super League', 'europe', 'sui.1'], ['Danish Superliga', 'europe', 'den.1'], ['Allsvenskan', 'europe', 'swe.1'], ['Eliteserien', 'europe', 'nor.1'],
    ['Greek Super League', 'europe', 'gre.1']];

export { Scudi, tkey, ALIASES, REG };
