"""The Edge Functions as ONE file each, for deploying them from Supabase's dashboard editor (decision 92):
supabase/functions/snai-pull/{logic.mjs,index.ts} → supabase/dashboard/snai-pull.ts (the logic first, then the function
without its import). The CLI or the connector deploy the files as they are; these copies are for the dashboard only.

Decision 95: scudi-notify reuses the page's own live maths, so its site.mjs is EXTRACTED from index.html (the Scudi engine
block, the team-name aliases, the competitions' ESPN slugs) and kept in step by this script too:
supabase/functions/scudi-notify/{site.mjs,push.mjs,alerts.mjs,index.ts} → supabase/dashboard/scudi-notify.ts.

    python3 tools/pack_function.py          # rebuild after changing the function
    python3 tools/pack_function.py --check  # exit 1 if the copy is out of date (the tests run this)
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "supabase" / "functions" / "snai-pull"
OUT = ROOT / "supabase" / "dashboard" / "snai-pull.ts"
NSRC = ROOT / "supabase" / "functions" / "scudi-notify"
NOUT = ROOT / "supabase" / "dashboard" / "scudi-notify.ts"
SITE = NSRC / "site.mjs"


def cut(html: str, start: str, end: str, keep_end: bool = False) -> str:
    a = html.find(start)
    b = html.find(end, a + 1) if a > -1 else -1
    if a < 0 or b < 0:
        raise SystemExit(f"index.html: block {start!r} … {end!r} not found")
    return html[a:b + (len(end) if keep_end else 0)]


def build_site() -> str:
    html = (ROOT / "index.html").read_text()
    engine = cut(html, "/* ===== Scudi slip maths", "if (typeof module !== 'undefined') module.exports = Scudi;")
    names = cut(html, "  var CLUB_WORDS =", "  function loadTeams() {")
    reg = cut(html, "  var REG = [", "  var GROUPS =")
    return ("// GENERATED by tools/pack_function.py from index.html — do not edit here (decision 95).\n"
            "// The page's own maths and names for the scudi-notify function: the Scudi engine block, the team-name aliases,\n"
            "// the competitions' ESPN slugs. Rebuilt whenever index.html changes; the tests check it is in step.\n"
            "/* eslint-disable */\n" + engine.rstrip() + "\n\n" + names.rstrip() + "\n\n" + reg.rstrip() + "\n\n"
            "export { Scudi, tkey, ALIASES, REG };\n")


def strip_imports(text: str, names: list[str], where: str) -> str:
    for n in names:
        text, k = re.subn(r"^import \{[^}]*\} from '\./" + re.escape(n) + r"';\n", "", text, flags=re.M)
        if k != 1:
            raise SystemExit(f"{where}: the import of {n} was not found")
    return text


def build_notify(site: str) -> str:
    push = (NSRC / "push.mjs").read_text()
    alerts = strip_imports((NSRC / "alerts.mjs").read_text(), ["site.mjs"], "alerts.mjs")
    index = strip_imports((NSRC / "index.ts").read_text(), ["push.mjs", "alerts.mjs"], "index.ts")
    site = site.replace("export { Scudi, tkey, ALIASES, REG };\n", "")
    unexport = lambda t: re.sub(r"^export (async function|function|const) ", r"\1 ", t, flags=re.M)
    head = ("// @ts-nocheck — the shared parts are plain JavaScript (typed checks run on the four-file version)\n"
            "// GENERATED by tools/pack_function.py from supabase/functions/scudi-notify/ — do not edit here.\n"
            "// Scudi · scudi-notify as one file for Supabase's dashboard editor: paste it whole as index.ts,\n"
            "// and switch off \"Verify JWT\" for the function (it checks its callers itself).\n\n")
    return (head + "// ===== site.mjs (from index.html) =====\n" + site.rstrip() + "\n\n// ===== push.mjs =====\n" + unexport(push).rstrip() +
            "\n\n// ===== alerts.mjs =====\n" + unexport(alerts).rstrip() + "\n\n// ===== index.ts =====\n" + index)


def build() -> str:
    logic = (SRC / "logic.mjs").read_text()
    index = (SRC / "index.ts").read_text()
    index, n = re.subn(r"^import \{[^}]*\} from '\./logic\.mjs';\n", "", index, flags=re.M)
    if n != 1:
        raise SystemExit("index.ts: the import of logic.mjs was not found")
    head = ("// @ts-nocheck — the logic part is plain JavaScript (typed checks run on the two-file version)\n"
            "// GENERATED by tools/pack_function.py from supabase/functions/snai-pull/ — do not edit here.\n"
            "// Scudi · snai-pull as one file for Supabase's dashboard editor: paste it whole as index.ts,\n"
            "// and switch off \"Verify JWT\" for the function (it checks its callers itself).\n\n")
    return head + "// ===== logic.mjs =====\n" + logic.rstrip() + "\n\n// ===== index.ts =====\n" + index


def main(argv: list[str]) -> int:
    site = build_site()
    outs = [(OUT, build()), (SITE, site)]
    if (NSRC / "index.ts").exists():
        outs.append((NOUT, build_notify(site)))
    if "--check" in argv:
        stale = [o for o, t in outs if not (o.exists() and o.read_text() == t)]
        print("dashboard functions up to date" if not stale else
              "OUT OF DATE: " + ", ".join(str(o.relative_to(ROOT)) for o in stale) + " — run python3 tools/pack_function.py")
        return 0 if not stale else 1
    for o, t in outs:
        o.parent.mkdir(parents=True, exist_ok=True)
        o.write_text(t)
        print(f"{o.relative_to(ROOT)}: {len(t) // 1024} KB")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
