"""The snai-pull Edge Function as ONE file, for deploying it from Supabase's dashboard editor (decision 92):
supabase/functions/snai-pull/{logic.mjs,index.ts} → supabase/dashboard/snai-pull.ts (the logic first, then the function
without its import). The CLI or the connector deploy the two files as they are; this copy is for the dashboard only.

    python3 tools/pack_function.py          # rebuild after changing the function
    python3 tools/pack_function.py --check  # exit 1 if the copy is out of date (the tests run this)
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "supabase" / "functions" / "snai-pull"
OUT = ROOT / "supabase" / "dashboard" / "snai-pull.ts"


def build() -> str:
    logic = (SRC / "logic.mjs").read_text()
    index = (SRC / "index.ts").read_text()
    index, n = re.subn(r"^import \{[^}]*\} from '\./logic\.mjs';\n", "", index, flags=re.M)
    if n != 1:
        raise SystemExit("index.ts: the import of logic.mjs was not found")
    head = ("// @ts-nocheck — the logic part is plain JavaScript (typed checks run on the two-file version)\n"
            "// GENERATED by tools/pack_function.py from supabase/functions/snai-pull/ — do not edit here.\n"
            "// Scudi · snai-pull as one file for Supabase's dashboard editor: paste it whole as index.ts,\n"
            "// and switch off \"Verify JWT\" for the function (it checks its callers itself).\n\n")
    return head + "// ===== logic.mjs =====\n" + logic.rstrip() + "\n\n// ===== index.ts =====\n" + index


def main(argv: list[str]) -> int:
    text = build()
    if "--check" in argv:
        ok = OUT.exists() and OUT.read_text() == text
        print("dashboard function up to date" if ok else "dashboard function OUT OF DATE: run python3 tools/pack_function.py")
        return 0 if ok else 1
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f"{OUT.relative_to(ROOT)}: {len(text) // 1024} KB")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
