-- Scudi · the same Scudi on every device, and notifications on the phone (decision 95)
-- 1. user_state: what the site keeps in the browser (placed slips, SNAI prices typed or read, learned margins, settings),
--    one row per key, readable and writable by the owner only, so the computer, Safari and the home-screen app agree.
-- 2. push_subs: the owner's devices that accepted notifications (Web Push: an endpoint and its two keys, no secret of ours).
-- 3. notify_sent: what was already notified (one row per alert), so nothing is sent twice.
-- 4. private.push_keys: the VAPID key pair the scudi-notify function signs with; generated by the function itself on its
--    first run and never leaving the database (the public half is handed to the site to subscribe).
-- 5. private.notify_memo: the final scores the function has read already, so a finished leg is not read again.

create table public.user_state (
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  key text not null check (key ~ '^scudi-[a-z0-9-]{1,40}$'),
  value jsonb not null check (octet_length(value::text) <= 2000000),
  updated_at timestamptz not null default now(),
  device text check (device is null or length(device) <= 40),
  primary key (user_id, key)
);
-- the database's clock, never a device's: the stamp that tells which copy is newer
create or replace function private.state_stamp() returns trigger
language plpgsql set search_path = '' as $$
begin new.updated_at := now(); return new; end;
$$;
create trigger scudi_state_stamp before insert or update on public.user_state for each row execute function private.state_stamp();
alter table public.user_state enable row level security;
create policy "the owner reads their state" on public.user_state for select to authenticated
  using (user_id = (select auth.uid()) and (select public.is_owner()));
create policy "the owner writes their state" on public.user_state for insert to authenticated
  with check (user_id = (select auth.uid()) and (select public.is_owner()));
create policy "the owner updates their state" on public.user_state for update to authenticated
  using (user_id = (select auth.uid()) and (select public.is_owner())) with check (user_id = (select auth.uid()));
create policy "the owner deletes their state" on public.user_state for delete to authenticated
  using (user_id = (select auth.uid()) and (select public.is_owner()));

create table public.push_subs (
  id bigint generated always as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  endpoint text not null unique check (endpoint ~ '^https://' and length(endpoint) <= 1000),
  p256dh text not null check (p256dh ~ '^[A-Za-z0-9_-]{80,100}$'),
  auth text not null check (auth ~ '^[A-Za-z0-9_-]{16,30}$'),
  ua text check (ua is null or length(ua) <= 60),
  created_at timestamptz not null default now(),
  last_ok timestamptz,
  fails int not null default 0
);
alter table public.push_subs enable row level security;
create policy "the owner reads their devices" on public.push_subs for select to authenticated
  using (user_id = (select auth.uid()) and (select public.is_owner()));
create policy "the owner removes a device" on public.push_subs for delete to authenticated
  using (user_id = (select auth.uid()) and (select public.is_owner()));

create table public.notify_sent (
  user_id uuid not null references auth.users (id) on delete cascade,
  ref text not null,
  at timestamptz not null default now(),
  title text,
  body text,
  primary key (user_id, ref)
);
alter table public.notify_sent enable row level security;
create policy "the owner reads what was sent" on public.notify_sent for select to authenticated
  using (user_id = (select auth.uid()) and (select public.is_owner()));

create table private.push_keys (
  id int primary key default 1 check (id = 1),
  public_key text not null,     -- base64url, uncompressed P-256 point (65 bytes)
  private_jwk jsonb not null,
  created_at timestamptz not null default now()
);
alter table private.push_keys enable row level security;

-- the final scores the function has already read (a leg decided is not read again), kept ten days
create table private.notify_memo (
  id int primary key default 1 check (id = 1),
  memo jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
alter table private.notify_memo enable row level security;

revoke all on public.user_state, public.push_subs, public.notify_sent from anon;
revoke truncate on public.user_state, public.push_subs from authenticated;
revoke insert, update, delete, truncate on public.notify_sent from authenticated;
revoke insert, update on public.push_subs from authenticated;
grant select, insert, update, delete on public.user_state to authenticated;
grant select, delete on public.push_subs to authenticated;
grant select on public.notify_sent to authenticated;

-- ---------- what the site calls (the owner's sign-in) ----------
-- several keys at once, each only if the copy it was based on is still the stored one (base = that copy's updated_at, as
-- text, null for a key not stored yet); otherwise the stored copy comes back, to be merged and sent again
create or replace function public.state_put(items jsonb) returns jsonb
language plpgsql security invoker set search_path = '' as $$
declare it jsonb; cur public.user_state; out jsonb := '[]'::jsonb; base timestamptz;
begin
  if not public.is_owner() then raise exception 'not the owner' using errcode = '42501'; end if;
  if jsonb_typeof(items) <> 'array' or jsonb_array_length(items) > 40 then raise exception 'bad items' using errcode = '22023'; end if;
  for it in select * from jsonb_array_elements(items) loop
    base := nullif(it ->> 'base', '')::timestamptz;
    select * into cur from public.user_state s where s.user_id = auth.uid() and s.key = it ->> 'key' for update;
    if (cur.key is null and base is null) or (cur.key is not null and cur.updated_at = base) then
      insert into public.user_state (user_id, key, value, device) values (auth.uid(), it ->> 'key', it -> 'value', left(it ->> 'device', 40))
      on conflict (user_id, key) do update set value = excluded.value, device = excluded.device
      returning * into cur;
      out := out || jsonb_build_object('key', cur.key, 'ok', true, 'at', cur.updated_at);
    else
      out := out || jsonb_build_object('key', it ->> 'key', 'ok', false, 'at', cur.updated_at, 'value', cur.value);
    end if;
  end loop;
  return out;
end;
$$;

-- this device accepted notifications: its endpoint and keys (a second call for the same endpoint refreshes them)
create or replace function public.push_add(sub jsonb) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare r public.push_subs;
begin
  if not public.is_owner() then raise exception 'not the owner' using errcode = '42501'; end if;
  insert into public.push_subs (user_id, endpoint, p256dh, auth, ua)
  values (auth.uid(), sub ->> 'endpoint', sub -> 'keys' ->> 'p256dh', sub -> 'keys' ->> 'auth', left(sub ->> 'ua', 60))
  on conflict (endpoint) do update set user_id = excluded.user_id, p256dh = excluded.p256dh, auth = excluded.auth, ua = excluded.ua, fails = 0
  returning * into r;
  return jsonb_build_object('id', r.id, 'devices', (select count(*) from public.push_subs p where p.user_id = auth.uid()));
end;
$$;
create or replace function public.push_remove(endpoint text) returns jsonb
language plpgsql security definer set search_path = '' as $$
begin
  if not public.is_owner() then raise exception 'not the owner' using errcode = '42501'; end if;
  delete from public.push_subs p where p.user_id = auth.uid() and p.endpoint = push_remove.endpoint;
  return jsonb_build_object('devices', (select count(*) from public.push_subs p where p.user_id = auth.uid()));
end;
$$;
revoke all on function public.state_put(jsonb), public.push_add(jsonb), public.push_remove(text) from public, anon;
grant execute on function public.state_put(jsonb), public.push_add(jsonb), public.push_remove(text) to authenticated;

-- ---------- what the scudi-notify function calls (secret key only) ----------
-- everything it needs in one call: the owner, their synced state (the keys it reads), their devices, the keys, the token check
create or replace function public.notify_load(cron text default null) returns jsonb
language sql stable security definer set search_path = '' as $$
  select jsonb_build_object(
    'cron_ok', cron is not null and length(cron) >= 32 and cron = (select c.cron_token from private.feed_config c where c.id = 1),
    'owner', (select o.user_id from public.owners o order by o.added_at limit 1),
    'state', coalesce((select jsonb_object_agg(s.key, s.value) from public.user_state s
                        where s.user_id = (select o.user_id from public.owners o order by o.added_at limit 1)
                          and s.key in ('scudi-placed', 'scudi-notify', 'scudi-lang')), '{}'::jsonb),
    'subs', coalesce((select jsonb_agg(jsonb_build_object('id', p.id, 'endpoint', p.endpoint, 'p256dh', p.p256dh, 'auth', p.auth, 'fails', p.fails))
                        from public.push_subs p where p.user_id = (select o.user_id from public.owners o order by o.added_at limit 1)), '[]'::jsonb),
    'keys', (select jsonb_build_object('public_key', k.public_key, 'private_jwk', k.private_jwk) from private.push_keys k where k.id = 1),
    'sent', coalesce((select jsonb_agg(n.ref) from public.notify_sent n
                       where n.user_id = (select o.user_id from public.owners o order by o.added_at limit 1) and n.at > now() - interval '3 days'), '[]'::jsonb),
    'memo', coalesce((select m.memo from private.notify_memo m where m.id = 1), '{}'::jsonb));
$$;

-- the VAPID key pair, stored once: a second call keeps the first pair
create or replace function public.notify_keys_init(pub text, priv jsonb) returns jsonb
language plpgsql security definer set search_path = '' as $$
begin
  insert into private.push_keys (id, public_key, private_jwk) values (1, pub, priv) on conflict (id) do nothing;
  return (select jsonb_build_object('public_key', k.public_key, 'private_jwk', k.private_jwk) from private.push_keys k where k.id = 1);
end;
$$;

-- which of these alerts were not sent yet (and claim them in the same breath, so two runs never send one twice)
create or replace function public.notify_claim(uid uuid, items jsonb) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare fresh jsonb;
begin
  with ins as (
    insert into public.notify_sent (user_id, ref, title, body)
    select uid, x.ref, x.title, x.body from jsonb_to_recordset(coalesce(items, '[]'::jsonb)) as x(ref text, title text, body text)
     where x.ref is not null
    on conflict (user_id, ref) do nothing
    returning ref)
  select coalesce(jsonb_agg(ref), '[]'::jsonb) into fresh from ins;
  delete from public.notify_sent where at < now() - interval '30 days';
  return fresh;
end;
$$;

create or replace function public.notify_memo_save(memo jsonb) returns void
language sql security definer set search_path = '' as $$
  insert into private.notify_memo (id, memo, updated_at) values (1, coalesce(memo, '{}'::jsonb), now())
  on conflict (id) do update set memo = excluded.memo, updated_at = now();
$$;

-- a device's delivery result: ok → last_ok; gone (404/410) → removed; other failures counted, removed after 10
create or replace function public.notify_result(sub_id bigint, ok boolean, gone boolean) returns void
language plpgsql security definer set search_path = '' as $$
begin
  if gone then delete from public.push_subs where id = sub_id; return; end if;
  if ok then update public.push_subs set last_ok = now(), fails = 0 where id = sub_id;
  else update public.push_subs set fails = fails + 1 where id = sub_id; delete from public.push_subs where id = sub_id and fails >= 10; end if;
end;
$$;

revoke all on function public.notify_load(text), public.notify_keys_init(text, jsonb), public.notify_claim(uuid, jsonb), public.notify_result(bigint, boolean, boolean),
  public.notify_memo_save(jsonb) from public, anon, authenticated;
grant execute on function public.notify_load(text), public.notify_keys_init(text, jsonb), public.notify_claim(uuid, jsonb), public.notify_result(bigint, boolean, boolean),
  public.notify_memo_save(jsonb) to service_role;
